### ISSUE TITLE
Simple UI xplr like ranger

### ISSUE THREAD

**Issue by Huxisher** [sayanarijit/xplr#107]
First Thanks for develop
Please make default UI simple like python/ranger and for TUI it's use config or something like xplr -s --simple as simple ui
simple ui -> xplr without selection,help section and maybe remove borders!
at the end, sorry for my bad English :)

**Comment by sayanarijit** [comment]
Hey, thanks for your feedback. I'll see how I can provide more UI options without losing its strong points.

**Comment by aecepoglu** [comment]
Being able to close panels from the config should be an easy start and something I'd like to be able to do

**Comment by sayanarijit** [comment]
I thought about this and came up with this idea:
- We should be able to define the `xplr` UI layout via the config file.
- A layout can contain either a `Vertical` split, or a `Horizontal` split, or a leaf node.
- Each (`Vertical` and `Horizontal`) split can have their own nested layouts.
- The leaf nodes will be the panels e.g. Table, SortNFilter, InputOrLog, Selection etc.
- Each layout size can be adjusted via config.

**Comment by aflyingpumpkin** [comment]
Another feature that could be added is different UI modes. Which would allow the creation of modes for preview (if and when it is implemented) , Simple UI, and for the normal UI.

**Comment by sayanarijit** [comment]
So just like we have `mode:`, we can have

```yaml
layout:
  builtin:
    default:
    ...
  custom:
    custom_layout1:
    ...
```

Then we can switch between layouts with `SwitchLayout: default`, `Switchayout:  custom_layout1`.

@maximbaz any feedback?

Speaking of modes, I'm also thinking about introducing 2 new messages `SwitchModeBuiltin: {mode}` and `SwitchModeCustom: {mode}` so that we can be more specific about which mode to switch to. The same can be done for the layout.

**Comment by aflyingpumpkin** [comment]
Pretty much. Also, distinguishing between user custom modes and built in modes sounds like a good idea.

**Comment by maximbaz** [comment]
This sounds very powerful! I like the idea with file preview, I also wonder if people from the `mc` will appreciate this to make a dual-panel file manager, if this will be allowed :)

**Comment by sayanarijit** [comment]
I don't think we can use the layout feature to manage multiple xplr sessions. It will complicate things. Bit yes, when we implement cli options, it will be helpful to be able to spawn new xplr sessions with hidden selection and help menu panels.

**Comment by sayanarijit** [comment]
^ Finally, PR ready for review.
