### ISSUE TITLE
Auto disown when opening in gui

### ISSUE THREAD

**Issue by aflyingpumpkin** [sayanarijit/xplr#108]
Upon opening an application in gui the current terminal window is still linked to the gui. Meaning that I cannot close it without it closing the GUI. I am also locked out of the current xplr session. Meaning I cannot browse other files after opening a single file. Upon closing the GUI application the GUI for xplr becomes messed up. (view attached image.)
![image](https://user-images.githubusercontent.com/49350251/116119066-fff76380-a68b-11eb-89a3-a765ecd24756.png)

**Comment by sayanarijit** [comment]
You can use `ctrl-r` to reset the screen. Or terminal resize should also work.

**Comment by sayanarijit** [comment]
@aflyingpumpkin let me know if ^ this works.

**Comment by aflyingpumpkin** [comment]
> @aflyingpumpkin let me know if ^ this works.
This does resolve the issues with the GUI.

**Comment by sayanarijit** [comment]
Should solve. I can't can test it now because my window manager will autoresize the screen which causes the refresh automatically.

**Comment by sayanarijit** [comment]
`CTRL+R` doesn't solve it? Can you pls provide more info like which OS, window manager, terminal are you using?
A [gif](https://github.com/phw/peek) would be awesome.

**Comment by aflyingpumpkin** [comment]
My window manager (dwm) also resizes the window upon closing the GUI. But I believe the GUI the process is not completely terminated when the window resizes which causes the buggy visuals. Also, I am locked out of xplr when the gui is open.

**Comment by sayanarijit** [comment]
Have you tried other terminals?

**Comment by aflyingpumpkin** [comment]
Just tried in Alacritty and the issue still persists.

**Comment by sayanarijit** [comment]
Which application are you trying to open?

**Comment by sayanarijit** [comment]
If I run `xdg-open x.doc`, it opens in Kate and works fine.

**Comment by sayanarijit** [comment]
Just FYI [this command](https://github.com/sayanarijit/xplr/blob/main/src/config.yml#L929-L930) is being executed.

**Comment by sayanarijit** [comment]
```
${OPENER:-open} "${XPLR_FOCUS_PATH:?}" &> /dev/null &
```
This might solve the issue but need to test it. @aflyingpumpkin can you try overwriting the command?

**Comment by aflyingpumpkin** [comment]
```${OPENER:-open} "${XPLR_FOCUS_PATH:?}" &> /dev/null & disown -h```
Fixes my issue though it does cause some text to be displayed on xplr when opening prior to window resize

**Comment by aflyingpumpkin** [comment]
![image](https://user-images.githubusercontent.com/49350251/116122069-4b5f4100-a68f-11eb-8d6b-8ceb0d8adb31.png)
is the text that appears

**Comment by sayanarijit** [comment]
And `ctrl+r` doesn't fix it?

**Comment by aflyingpumpkin** [comment]
``ctrl+r`` fixes it, and it usually goes away when the application is opened unless I am in fullscreen mode.

**Comment by sayanarijit** [comment]
Hmm... not sure how to workaround this without a proper testing environment. @aflyingpumpkin if possible, can you pls create a PR?

**Comment by aflyingpumpkin** [comment]
What is a PR?

**Comment by sayanarijit** [comment]
A [pull request](https://docs.github.com/en/github/getting-started-with-github/github-glossary#pull-request) with the fix. No problem, I can do this.

**Comment by aflyingpumpkin** [comment]
Just found out that the random text was due to me accidentally putting:
``                  OPENER="$(which xdg-open $)"``
instead of
``                  OPENER="$(which xdg-open)"``

**Comment by sayanarijit** [comment]
Ah ok.. Unfortunately the `disown` hack is causing other side effects. After I exit the session, the terminal session is messed up if there are disowned jobs. I think we need to investigate more into this.

**Comment by sayanarijit** [comment]
Nope, that was my fault. I used `disown` incorrectly and didn't exit the terminal.

**Comment by sayanarijit** [comment]
Weird... Not in my WM...

**Comment by sayanarijit** [comment]
I'll setup a test VM will dwm when I get some time. Meanwhile, @aflyingpumpkin you can experiment with different command combinations and let me know if you found anything that works.

**Comment by sayanarijit** [comment]
Although if it's too hacky, we'll probably need to report the issue to DWM maintainers.

**Comment by maximbaz** [comment]
I got a ping on the (now closed) PR, to be honest I can't reproduce the issue on latest `main` (kitty, sway, arch) - i can open multiple files using `gx`, I can then close xplr, close terminal, and all gui app will remain and will function properly 🤷‍♂️

**Comment by aflyingpumpkin** [comment]
What I have been doing. I noticed that ``disown -h`` appears to not be needed ``${OPENER:-open} "${XPLR_FOCUS_PATH:?}" &> /dev/null &`` does the same thing.

Also, I just booted up i3 and the issue is still persisting.

**Comment by maximbaz** [comment]
What's your `$OPENER`? I recently discovered that `xdg-open` is quite weird sometimes, after I forced it to be an alias to `gio open` my life became so much better and random bugs just went away. Could it be this case too? 🤔 

My solution was to simply create an executable script called `~/.local/bin/xdg-open` with the contents below (assuming `~/.local/bin` is first in `$PATH`):

```sh
#!/bin/sh

gio open "$@"
```

Maybe worth a try for you too? Do this, open new terminal, double check that `which xdg-open`  now points to it, and then retry.

**Comment by aflyingpumpkin** [comment]
I am using xdg-open, after doing a force alias the bug still persists.

**Comment by aflyingpumpkin** [comment]
I think it may be a problem with disown. Currently only having the & symbol is needed, and ``disown -h`` should block the termination signal from doing anything.

**Comment by sayanarijit** [comment]
@aflyingpumpkin I was using plain `disown`, not `disown -h`.

**Comment by sayanarijit** [comment]
Try this: https://github.com/sayanarijit/xplr/pull/109/files

**Comment by aflyingpumpkin** [comment]
I saw, even when I use what was put in the pull request the issue still exists.

**Comment by sayanarijit** [comment]
Maybe it's WM specific bug? Need to test it on different window managers. So far as we know,

KDE + KWin     -> Working
SWAY (I3)         -> Working
DWM                 -> Broken
GNOME            -> Not tested
I3 (stock)           -> Not tested
I3-status            -> Not tested
BSPWM            -> Not tested
AwesomeWM   -> Not tested
qtile                   -> Not tested
xmonad             -> Not tested

**Comment by aflyingpumpkin** [comment]
I have tried stock i3 and it appears to be broken.

**Comment by sayanarijit** [comment]
I wish I had more users in our [discord](https://discord.gg/p8UPpgAx) channel, then I could just ping users to test this :smile:

**Comment by aflyingpumpkin** [comment]
Just tried kwin with alacritty and kitty and I am still running into the issue. I also tried switching to zsh and I am still running into the issue.

**Comment by sayanarijit** [comment]
Wow, then it seems more like a platform issue? Which OS are you using?

**Comment by aflyingpumpkin** [comment]
I use arch btw

**Comment by sayanarijit** [comment]
And maybe shell?

**Comment by aflyingpumpkin** [comment]
I tried on both zsh and bash.

**Comment by sayanarijit** [comment]
Very strange. I'm out of ideas. Can you record a video? I think GitHub allows posting video files.

**Comment by aflyingpumpkin** [comment]
https://user-images.githubusercontent.com/49350251/116135126-b82e0780-a69e-11eb-9286-7256c90463bd.mp4

**Comment by sayanarijit** [comment]
![image](https://user-images.githubusercontent.com/11632726/116135382-b5f39980-a6ee-11eb-8084-697e752085e5.png)

GitHub broke :smile:

**Comment by aflyingpumpkin** [comment]
No, I deleted the message because the aspect ratio was messed up.
https://user-images.githubusercontent.com/49350251/116135449-28d52400-a69f-11eb-9664-f58095b81292.mp4

**Comment by sayanarijit** [comment]
@aflyingpumpkin you can maybe also capture a GIF using https://github.com/phw/peek. Preferably the KDE-Kwin one.

**Comment by sayanarijit** [comment]
> No, I deleted the message because the aspect ratio was messed up.
> https://user-images.githubusercontent.com/49350251/116135449-28d52400-a69f-11eb-9664-f58095b81292.mp4

Runs on VLC

**Comment by sayanarijit** [comment]
It the video `xplr` seems to work fine? You opened the file, then closed `xplr`?

**Comment by aflyingpumpkin** [comment]
The first example where they both closed at the same time was when I left xplr open and closed the terminal. The second example when the document stayed open was due to the fact that I fist closed xplr then closed the terminal.

**Comment by sayanarijit** [comment]
Ah okay, so that's when you meant.

**Comment by sayanarijit** [comment]
Yes I can reproduce this. I don't think you're supposed to close th eterminal before quitting `xplr` gracefully.

**Comment by sayanarijit** [comment]
The document will stay open. You close it separately. It's the expected behavior I guess.

**Comment by sayanarijit** [comment]
Or, if you want to open multiple documents, you can do so, but you need to close them manually and quit `xplr` gracefully.

**Comment by sayanarijit** [comment]
You can probably achieve what you want to, using `nohup` or `screen` or `tmux`. But I don't think it should be the default in `xplr`.

**Comment by aflyingpumpkin** [comment]
Alright, thanks

**Comment by sayanarijit** [comment]
@aflyingpumpkin [v0.9.1](https://github.com/sayanarijit/xplr/releases/tag/v0.9.1) probably fixed the issue in a way you wanted. You can close the terminal after opening apps in GUI, without closing them.

**Comment by aflyingpumpkin** [comment]
Great!
