### ISSUE TITLE
Similar colour for a directory and cursor on Mac

### ISSUE THREAD

**Issue by suryasr007** [sayanarijit/xplr#11]
I like the package. It's light(below 1 MB). 

It seems like color for a directory and cursor on Mac are the same which is a bit confusing.

![image](https://user-images.githubusercontent.com/10533926/113667798-eb4c2f00-96ce-11eb-9f70-d93ddd6a0d34.png)

**Comment by sayanarijit** [comment]
Good find. This will be addressed in the next release.
