### ISSUE TITLE
CD to directory instead of just exiting with directory printed

### ISSUE THREAD

**Issue by jake-87** [sayanarijit/xplr#110]
I personally think there should at least be a config option to cd to a directory instead of just exiting, printing the directory. While i do not know much rust, I believe this could be achieved with `std::process::Command`, which should allow directory management.

**Comment by sayanarijit** [comment]
Hi @jake-87 if I understand the intention correctly, there are many ways to achieve that.

- Using  a ahell alias `alias xdd='cd $(xplr)/'`. When you press `enter` while focusing on a dir, you will cd into it.
- Invoking the built-in terminal. You can invoke the terminal using `:!` and you will drop into `bash` in the same dir. Although, when you exit the terminal, you will return to the `xplr` session.
- Invoke a new terminal session when you are inside the target directory (works with Alacrity, might also work with other terminal emulators).
  e.g. Let's say you are using Alacrity (latest). Now in `xplr` you are inside `/tmp/xplr`. Now when you open a new Alacrity window using `cmd+n`, it will open in `/tmp/xplr`.

**Comment by sayanarijit** [comment]
@jake-87 if I missed something, let me know the use case to that I can suggest better ways or if possible, integrate natively into `xplr`.

**Comment by maximbaz** [comment]
> Invoke a new terminal session when you are inside the target directory (works with Alacrity, might also work with other terminal emulators).

Wow I didn't know of this feature! Very cool! works in kitty too 😉 

> Invoking the shell. You can invoke the shell using :! and you will drop into bash in the same dir.

Don't want to hijack the thread, we can move to another one - but why `bash` is hardcoded? Why don't we start default shell, like nnn does for example?

**Comment by sayanarijit** [comment]
@maximbaz currently there's some issue with ohmyzsh. https://github.com/ohmyzsh/ohmyzsh/issues/9859

I'm sure more than half zsh users are using ohmyzsh, so waiting for this to fix.

**Comment by sayanarijit** [comment]
Just FYI, I have started publishing daily scheduled tips [on our discord](https://discord.gg/p8UPpgAx). Although, there is [another shortcut](https://github.com/sayanarijit/xplr-bots/blob/main/tips.txt).

**Comment by sayanarijit** [comment]
I hope this was answered. Closing this issue.

**Comment by macintacos** [comment]
Can this be reopened? Opening a new shell is less than optimal, for example when the shell you opened the xplr session from contains environment variables or a virtual environment that you want to keep when you end up "cd-ing" to it, opening a new shell session loses that information.

Ideally, when hitting `q` after navigating to a directory, you'd exit and be brought to the directory you were just in. That would feel the most intuitive.

**Comment by maximbaz** [comment]
@macintacos it's already possible, add this to your `.zshrc`:

```zsh
x() { PAGER="less -+F" xplr | IFS= read -r dir && cd -- "${dir:-.}" }
```

With this alias, `q` would exit as normal, but `:qp` would exit and move to the directory you were just in. Then you can override the default mappings of `q` to do what `:qp` does.

**Comment by macintacos** [comment]
Thanks, I use Fish but I'll work with that!

**Comment by sayanarijit** [comment]
The newer version of xplr has a convenient argument `--print-pwd-as-result` that can be used for cd on quit. See https://xplr.dev/en/awesome-hacks#cd-on-quit

**Comment by PhML** [comment]
@macintacos I also use fish and I came to this fish configuration:
```fish
function fish_user_key_bindings
    bind \el __fish_xplr
end

function __fish_xplr -d "Keep xplr result on command line"
    commandline -a (command xplr)
end
```
So that I open `xplr` with `Alt-L` and when I quit the result is on the commandline I just have to type `cd` or whatever command I’d like to use with the result.

The default for `Alt-L` in fish is to run `ls` in current directory but I don’t use it.
