### ISSUE TITLE
Window drawing glitch in i3 after opening LibreOffice

### ISSUE THREAD

**Issue by auronandace** [sayanarijit/xplr#111]
I tried opening a file in a folder using the 'go to' action and then pressing x to open with gui. With a txt file it decided to open with LibreOffice and my window manager (i3) automatically resizes the terminal and LibreOffice. When I close LibreOffice then the terminal with xplr resizes to the original size but some of the ui drawing is missing:

![gscreenshot_2021-04-27-145500](https://user-images.githubusercontent.com/81362994/116253781-b0d33080-a768-11eb-9724-3d4bf92d7e7d.png)

The frames seem to be gone. That was where LibreOffice was open. If I open something else and then close that then the frames are drawn properly again.

**Comment by sayanarijit** [comment]
Hey, does ctrl+r help in restoring the screen?

**Comment by auronandace** [comment]
> Hey, does ctrl+r help in restoring the screen?

Yes, it puts it back to normal.

**Comment by sayanarijit** [comment]
Great, I'm not sure if it's caused by i3 or libre or something else. It's difficult to reproduce because I'm using kde+kwin. Can you help in investigating the underlying cause?
If that sounds good, you can try opening other apps, play with `~/.config/mimeapps.list` etc. Let me know when things work, when things break.

**Comment by auronandace** [comment]
I've managed to trigger it with the following applications:

feh
LibreOffice
Evince
mpv

It seems to trigger more often than not but on some occasions (using the same apps) it doesn't. I can't pinpoint exactly what causes it. I'm just using the exact same process.

**Comment by auronandace** [comment]
Some extra information:

In the original post I was using alacritty as the terminal. I've tested it in a few other terminals:

kitty - shows a different visual glitch
terminology - the terminal goes blank until you close the application you just opened
xfce4-terminal - sometimes freezes for a few seconds after closing LibreOffice
qterminal - same as xfce4-terminal

LibreOffice is certainly the application that triggers the issues most consistently.

**Comment by sayanarijit** [comment]
@auronandace Thanks for the detailed report. I think it will help me fix the issue. I'll ping you for review once I create a fix.

**Comment by auronandace** [comment]
Another important detail I should mention is that when you open another app from within xplr in i3 the terminal obviously automatically resizes but the terminal contents don't change at all so it looks as if the new app is overlapping the terminal but it clearly isn't.

I think xplr just isn't detecting that the terminal has been resized when it opens a gui app so that xplr isn't redrawing itself:

![gscreenshot_2021-04-27-181544](https://user-images.githubusercontent.com/81362994/116283645-01a45280-a784-11eb-9c43-9c3ea40831eb.png)

**Comment by sayanarijit** [comment]
Released [v0.5.8](https://github.com/sayanarijit/xplr/releases/tag/v0.5.8). Binaries should be available in a few minutes.

**Comment by sayanarijit** [comment]
Thanks @auronandace & @aflyingpumpkin for the bug report and PR reviews.
