### ISSUE TITLE
Sort help menu by description

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#151]
More details: https://github.com/sayanarijit/xplr/discussions/146#discussioncomment-740168

**Comment by dtomvan** [comment]
Why not make a config entry for it? A lot of sorting is already done using the lua config and it would be much more flexible.

**Comment by sayanarijit** [comment]
Maybe we can make it a lua functions. The backend functionality is already there. That way we can organize and style it the way we like. We don't even need to worry about the performance since the modes are static and we can just pre-render them when xplr loads.

**Comment by sayanarijit** [comment]
With the custom layouts implemented, this should be easy to implement custom help menu using DynamicTable or DynamicList. See https://xplr.dev/en/layout#dynamic-table

Closing this.
