### ISSUE TITLE
Using Case Statement with Mimetypes

### ISSUE THREAD

**Issue by IcyFlamingArrow** [sayanarijit/xplr#154]
Hello,

I am experiencing difficulties implementing a simple bash script due to my lack of experience.

`              - BashExec: | `
                      `case $(file --mime-type -b $(cat "${XPLR_PIPE_RESULT_OUT:?}") ) in`
                           ` video/*) mpv $(cat "${XPLR_PIPE_RESULT_OUT:?}")`
                               `< "${XPLR_PIPE_RESULT_OUT:?}") ;;`
`esac`

`-PopMode`
`-Refresh`

This did not work on my computer either,
`              - BashExec: | `
`case $(file --mime-type -b $(cat "${XPLR_PIPE_RESULT_OUT:?}") ) in`
`video/*) (while IFS= read -r line; do`
`mpv "${line:?}"`
 `done < "${XPLR_PIPE_RESULT_OUT:?}") ;;`

The other cases are effective though,

`text/*) (while IFS= read -r line; do`
`nvim "${line:?}"`
 `done < "${XPLR_PIPE_RESULT_OUT:?}") ;;`

What am I doing incorrectly?

I greatly appreciate your assistance with my inexperience with scripting. 😀

**Comment by sayanarijit** [comment]
I'd recommend writing the script in a file (let's say `script.sh`) then from `xplr`, press `:!` to get into the interactive shell. Then run the script with `bash script.sh`. Finally, when the script runs successfully, exit the shell to see if it does what you wanted.

Also, I can't see the script properly. You can format your code like this: https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code.

**Comment by IcyFlamingArrow** [comment]
Thank you for the prompt assistance!!! 😄

This is the `case.sh` script I have created:

```
#!/bin/sh
case $(file --mime-type -b "$(cat "${XPLR_PIPE_RESULT_OUT:?}")" ) in
                      text/*) (while IFS= read -r line; do
                              nvim "${line:?}"
                              done < "${XPLR_PIPE_RESULT_OUT:?}") ;;
                      video/*) (while IFS= read -r line; do
                               devour mpv "${line:?}"
                               done < "${XPLR_PIPE_RESULT_OUT:?}") ;;
                      image/*) (while IFS= read -r line; do
                               devour sxiv "${line:?}"
                               done < "${XPLR_PIPE_RESULT_OUT:?}") ;;
                           esac
```

and this is the relevant portion in my config.yml now

```       enter:
              help: Open File 
              messages:
                - BashExec: |
                      case.sh
                - PopMode
```
Xplr is now successfully opening the video files according to its mime type thanks to your suggestion of a separate script.

**Comment by sayanarijit** [comment]
You might want to use `XPLR_FOCUS_PATH` because `XPLR_PIPE_RESULT_OUT` is sum of `XPLR_PIPE_FOCUS_PATH` and `XPLR_PIPE_SELECTION_OUT`, which can be multiline.

`XPLR_FOCUS_PATH` is a single file, hence, you don't need to `cat` it. The value is directly available.

Also, I'd use redefined variables instead of playing with nested quotes.

```
MIME_TYPE=$(file --mime-type -b "$XPLR_FOCUS_PATH")
case "$MIME_TYPE" in
...
```

**Comment by IcyFlamingArrow** [comment]
I have improved the syntax according to your kind suggestions and this is the resulting `case.sh`

```
#!/bin/sh

MIME_TYPE=$(file --mime-type -b  "$XPLR_FOCUS_PATH" )

case "$MIME_TYPE" in
            text/*)   nvim "$XPLR_FOCUS_PATH" ;;
            video/*)  devour mpv "$XPLR_FOCUS_PATH" ;;
            image/*)  devour sxiv "$XPLR_FOCUS_PATH" ;;
esac
```

**Comment by IcyFlamingArrow** [comment]
On GitHub, the Authors should close an issue instead of the reporter, correct?

I apologize about my lack of etiquette with regards to GitHub.

And again, thank your for your generous and prompt assistance with the script. 😄

**Comment by sayanarijit** [comment]
Hey, No issue. No need to be so formal (with me at least) either :)
Normally AFAIK authors closing issues without proper resolution feels rude to the user, so the user is expected to close the issue when satisfied with the resolution. Although, I think this issue was resolved, I was deciding whether to close it because this info could be useful to other users.

**Comment by sayanarijit** [comment]
I'll close it.

**Comment by IcyFlamingArrow** [comment]
Could it be possible to share this as a hack in order to allow people to conveniently aware of the relevant code and thus adapt it for their personal uses?

**Comment by sayanarijit** [comment]
Maybe, but with the current implementation, you can define gui openers using some mime related config file depending on your distro/desktop environment/window manager. And you can set the editor using $EDITOR. But I'm not sure which way is better.

**Comment by sayanarijit** [comment]
E.g. ~/.config/mimeapps.list

**Comment by IcyFlamingArrow** [comment]
I did not consider portability in my initial script. WIth `$EDITOR` that is typically defined by the user in a another location such as `.profile`. This would make it indeed more optimal to defining a specific editor. 

I have just tested with with gedit as `$EDITOR` and there are no issues on my end, though I am unaware of how to separate the process of gedit from the current terminal with Xplr with `disown`.

With your concern with defining mimeapps vs variables such as EDITOR, the user can change the editor in any script. In my case.sh, I can export the editor to be sublime or kakoune or gedit for specifically Xplr.


Please do correct me for my incomplete comprehension if it is showing.

```
#!/bin/sh

export EDITOR='gedit'

MIME_TYPE=$(file --mime-type -b  "$XPLR_FOCUS_PATH" )

case "$MIME_TYPE" in
            text/*)   $EDITOR "$XPLR_FOCUS_PATH" ;;
            video/*)  devour mpv "$XPLR_FOCUS_PATH" ;;
            image/*)  devour sxiv "$XPLR_FOCUS_PATH" ;;
esac
```

**Comment by sayanarijit** [comment]
`$EDITOR` is generally defined globally e.g. in `.profile` and calls a terminal blocking app. It is not disowned. There are many programs e.g. `git commit` that will open the `$EDITOR` and wait until you close it, then proceed with the next step. If you use a GUI editor or disown the process, they might misbehave.

`xplr` also supports `$OPENER` variable that can be set to a custom opener. So, you can set `export EDITOR=nvim` and `export OPENER=case.sh`. You might want to handle the default case (`*`) with the GUI opener of your choice like `xdg-open` that will scan the `~/.config/mimeapps.list` file and open apps based on the definition there. You can also directly edit the `~/.config/mimeapps.list` itself. That could be a better solution than using a custom script.

**Comment by sayanarijit** [comment]
Updating `~/.config/mimeapps.list` might require re-login.

**Comment by IcyFlamingArrow** [comment]
So instead of utilizing a separate script to open certain filetypes, it would be preferred to open them with xdg-open like this
```
modes:
  builtin:
    default:
      key_bindings:
        on_key:
          enter:
            help: Open File 
            messages:
              - BashExec: |
                  xdg-open "$XPLR_FOCUS_PATH"
              - PopMode
              - Refresh
```

Along with a `~/.config/mimeapps.list` that appears in a manner like this
```
[Default Applications]

text/html=brave-browser.desktop;
text/plain=org.gnome.gedit.desktop;
```
in order to perform this task, opening files within Xplr according to their extension, more efficiently and universally on my computer. 

Implementing the changes in the `~/.config/mimeapps.list` does not require a re-login.

What is meant by a "GUI opener"?

Thank you

**Comment by sayanarijit** [comment]
Gui opener = xdg-open and alternatives

I didn't map `enter` to the opener on purpose. I think enter to return the file path is more useful because you can do a lot of more things with the returned path than just opening them.

**Comment by sayanarijit** [comment]
But you are free to remap them to whatever you find useful according to your workflow. `xplr`'s dedign goal is to allow you to customize it with the least amount of effort.

**Comment by IcyFlamingArrow** [comment]
Thank you for your clarifications and suggestions.
