### ISSUE TITLE
error: EOF while parsing a value

### ISSUE THREAD

**Issue by 1m-N00b** [sayanarijit/xplr#155]
xplr cant work

**Comment by sayanarijit** [comment]
Hi, Can you please provide more information like your machine, os, terminal, xplr version or how did you install xplr and what command are you running?

**Comment by 1m-N00b** [comment]
Thank you for your quick answer!

os:Arch
terminal:kitty
version:xplr-0.9.1-1(with `pacman -Syu xplr`not -git or -bin)
command is simply `xplr` in home

**Comment by sayanarijit** [comment]
Weird! Need some more info. Have you created a config file in `~/.config/xplr/config.yaml`? If yes can pls post the content.

**Comment by 1m-N00b** [comment]
I rewrote the version in config and it fixed it.
