### ISSUE TITLE
Xplr Invalid Behavior

### ISSUE THREAD

**Issue by IcyFlamingArrow** [sayanarijit/xplr#158]
In Xplr, whenever a key is pressed that is not mapped, it brings Xplr into another mode where the I have to exit using `esc` and the relevant output is `WARNING | Key map not found. Let's calm down, escape, and try again.`

How can I override/void this behavior in the config; ignore invalid keystokes?

Sorry to bother you again today. 😅

**Comment by sayanarijit** [comment]
Thanks for reporting. This "feature" was added to save the users from typing unwanted keys when they're typing recklessly. If one of the combo keys is invalid, I think it's better to go to recover mode any reject any further key presses than doing weird things.

However, I think a config parameter can be added to avoid it if it's bothering too much.

**Comment by IcyFlamingArrow** [comment]
The decision is up to you the maintainer and coder of Xplr. The most inconvenience this is to me is minor, but I am only one user. This is only inconvenient because I only utilize the Table. This is probably a rare use case for Xplr since the help menu and selection menu can be of great visual aid and most likely used by the majority of the other users.

**Comment by sayanarijit** [comment]
Will it help if the current more is displayed on the table header instead of the help menu? Or do you want to dust disable the `recover` mode?

**Comment by IcyFlamingArrow** [comment]
The current mode on the table header is a nifty idea. How can I set that following the title in the `config.yml`?

https://ibb.co/4pVjdDG

**Comment by sayanarijit** [comment]
![image](https://user-images.githubusercontent.com/11632726/118590867-e1831480-b7c0-11eb-82c8-3b2d27703769.png)

Probably like this.

Another option is to add a vim-like status bar.

**Comment by sayanarijit** [comment]
> How can I set that following the title in the config.yml?

It's not possible as of now. I'm just gathering info to reach a decision of how it can be implemented.

**Comment by IcyFlamingArrow** [comment]
There is no issue with your implementation that I can critique. It performs its function and is not obtrusive on the user interface.

**Comment by IcyFlamingArrow** [comment]
Also, your link to the messages links to version 0.4.4. [https://docs.rs/xplr/0.4.4/xplr/app/enum.ExternalMsg.html#variants](url)

The link should be 
[https://docs.rs/xplr/0.10.0-beta.0/xplr/app/enum.ExternalMsg.html#variants](url)

**Comment by sayanarijit** [comment]
Added support for displaying the mode in Input/Logs panel in https://github.com/sayanarijit/xplr/pull/190

**Comment by sayanarijit** [comment]
![image](https://user-images.githubusercontent.com/11632726/119313111-ca489900-bc90-11eb-8fb2-45585d4d580a.png)

![image](https://user-images.githubusercontent.com/11632726/119313139-d2083d80-bc90-11eb-93b4-5af8b956d071.png)

**Comment by sayanarijit** [comment]
Published https://github.com/sayanarijit/xplr/releases/tag/v0.11.0. Hope this resolved the issue. Feel free to reopen if not.
