### ISSUE TITLE
Migrate hacks and themes to Lua

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#182]
With `v0.10.0`, xplr no longer supports `config.yml`. Hence, We'll have to port the [hacks](https://github.com/sayanarijit/xplr/wiki/Hacks) and [themes](https://github.com/sayanarijit/xplr/wiki/Themes) to `Lua` equivalent.

A few hacks have [already been ported](https://github.com/sayanarijit/xplr/wiki/Hacks#fuzzy-search-with-preview) to `Lua`. Using this, [the tutorial](https://github.com/sayanarijit/xplr/wiki/Key-Bindings#tutorial-adding-a-new-mode) and [init.lua](https://github.com/sayanarijit/xplr/blob/main/src/init.lua) as reference, We need to port the remaining hacks and themes.

**TIP:** Use [xplr-yml2lua](https://github.com/sayanarijit/xplr-yml2lua) to make life easier.

**Comment by sayanarijit** [comment]
Even better, make them plugin-like, that can be attached using `require(foo).setup()`.

**Comment by sayanarijit** [comment]
Visit the https://arijitbasu.in/xplr/en/writing-plugins.html documentation.

**Comment by dtomvan** [comment]
I thought I'd help you out with one: [https://github.com/dtomvan/paste.rs.xplr](https://github.com/dtomvan/paste.rs.xplr)

**Comment by sayanarijit** [comment]
Hey awesome thanks 👍

**Comment by sayanarijit** [comment]
For future contributors,

Don't forget to [update docs](https://github.com/sayanarijit/xplr/edit/main/docs/en/src/awesome-plugins.md) and create a PR to add your plugin here: https://xplr.dev/en/awesome-plugins.
