### ISSUE TITLE
error: Directory not empty (os error 66)

### ISSUE THREAD

**Issue by amancevice** [sayanarijit/xplr#184]
I'm seeing `error: Directory not empty (os error 66)` after every command on my M1 iMac. Even simply, `xplr` then `q`

**Comment by sayanarijit** [comment]
Hey, are you using the latest version `v0.10.1`?

**Comment by sayanarijit** [comment]
It should have been fixed in https://github.com/sayanarijit/xplr/releases/tag/v0.10.0

**Comment by amancevice** [comment]
Looks like I'm using `0.9.1` — I installed with Homebrew

**Comment by sayanarijit** [comment]
It will take some time for the latest version to be available via `brew` (typically 2-3 days).
Unfortunately I can't build the aarch64 version in my regular mac. So, for now, you can install it using `cargo install --force xplr`.

**Comment by sayanarijit** [comment]
Brew seems to be updated. Closing this.
