### ISSUE TITLE
`runtime error: [string "init"]:2041: attempt to index fie...`

### ISSUE THREAD

**Issue by RustemB** [sayanarijit/xplr#185]
it's replaces in xplr (in my case) for `~/.steampath` symlink

**Comment by RustemB** [comment]
Oh, i got, it is config
```lua
    if m.symlink.is_dir then
      r = r .. "/"
    end
```
it's errors here

**Comment by RustemB** [comment]
actualy it's "broken" symlink

**Comment by sayanarijit** [comment]
Thanks for reporting the issue.

**Comment by sayanarijit** [comment]
Fixed in https://github.com/sayanarijit/xplr/releases/tag/v0.10.2
