### ISSUE TITLE
0.12.1 doesn't displays icons for files with specific extenstions, for dirs and some others

### ISSUE THREAD

**Issue by RustemB** [sayanarijit/xplr#199]

**Comment by sayanarijit** [comment]
Can you please provide examples of the files and extensions? Also, maybe a screenshot?

**Comment by sayanarijit** [comment]
Have you specified the version?

**Comment by RustemB** [comment]
> Have you specified the version?

yes, but also i modulize this by `require`ing this file from `init.lua`

**Comment by sayanarijit** [comment]
Hmm the path is relative. It works when you write the module in PWD.

**Comment by RustemB** [comment]
it works for prev versions, prbbly you broke something

**Comment by sayanarijit** [comment]
> it works for prev versions, prbbly you broke something

Not sure... I couldn't make any prev version work.

However, you need to add

```lua
package.path = os.getenv("HOME") .. '/.config/xplr/?/init.lua'
```

to your config file. Since we're not yet sure how we'll do plugin system, I'm not making it default as of now.

You can probably implement a plugin system yourself.

**Comment by sayanarijit** [comment]
Here [a basic plugin system](https://github.com/sayanarijit/.files/tree/Linux/nixpkgs/files/xplr).

cc @maximbaz (if you want to refactor your config).

**Comment by RustemB** [comment]
i'll just lay it here
https://github.com/RustemB/xplr

**Comment by sayanarijit** [comment]
@RustemB you don't need to copy the whole config. You can overwrite only what you want to modify.

**Comment by sayanarijit** [comment]
e.g. https://github.com/sayanarijit/.files/blob/Linux/nixpkgs/files/xplr/init.lua

**Comment by RustemB** [comment]
I know, but I copy this as reference, while there is not full documentations

**Comment by sayanarijit** [comment]
Ah ok.. Then you probably want to comment out the default parts of the config.

**Comment by sayanarijit** [comment]
Closing this assuming it's resolved.
