### ISSUE TITLE
Colors doesn't works if custom icon i specified

### ISSUE THREAD

**Issue by RustemB** [sayanarijit/xplr#200]
I started using Nerdfonts and change Download folder icon in `xplr.config.node_types.extension` now it doesn't colors

![image](https://user-images.githubusercontent.com/25725953/119721910-283dd200-be85-11eb-8b4b-9e5987902cf7.png)

**Comment by sayanarijit** [comment]
Fixed in https://github.com/sayanarijit/xplr/releases/tag/v0.13.0
