### ISSUE TITLE
Optimization with User Interface

### ISSUE THREAD

**Issue by IcyFlamingArrow** [sayanarijit/xplr#240]
Hello again,

I am wondering how to reduce the UI lag for my use case.

```
      right = {
        help = "enter",
        messages = { 
            {
                BashExec = [===[
                xplr_conditional.sh
                ]===]
            }
        }
      },
```
xplr_conditional.sh
```
[ -d "$XPLR_FOCUS_PATH" ] && echo "Enter" >> "$XPLR_PIPE_MSG_IN" || launch "$XPLR_FOCUS_PATH"
```

This creates substantial input lag, on occasions a 2 second delay, when browsing directories with `up` and `down`.

Thank you for your time. 

I am using the latest version of xplr  built with `cargo build` (0.14.0) this morning.

Operating System = Linux
Terminal = St

**Comment by IcyFlamingArrow** [comment]
The issue is no longer present after installing from the Arch repository. My apologies.

**Comment by sayanarijit** [comment]
Hi, when you build using cargo, use the `--release` flag to get the optimized binary.

**Comment by IcyFlamingArrow** [comment]
Thank you, my lack of inititiative regarding these matters such as this one where reading the documentation would have resolved my issue sooner is unfortunate. 

Thank you for telling me the proper way to optimally build using cargo.

**Comment by sayanarijit** [comment]
No worries. We're all learners.
