### ISSUE TITLE
add the application to the void repo?

### ISSUE THREAD

**Issue by Relected** [sayanarijit/xplr#242]
hello, i think it would  be pretty cool if void linux users can download the pkg using xbps without the need to compile from source :)

**Comment by sayanarijit** [comment]
Hi, thanks for the suggestion. I haven't tested it but any linux or macos user should be able to directly download and run the pre-built binary from the [releases](https://github.com/sayanarijit/xplr/releases).

BTW I only maintain the crate and nixpkgs version. Packages for other repositories are maintained by the community. If you know any void linux repository maintainer who might be interested in maintaining xplr, you can probably inform/request them.

**Comment by sayanarijit** [comment]
@subham-cpp created https://github.com/shubham-cpp/void-pkg-templates with instructions for setup.

**Comment by sayanarijit** [comment]
Closing this issue. Please feel free to reopen if there's some concern.
