### ISSUE TITLE
FocusPath doesn't focus full path on the first try

### ISSUE THREAD

**Issue by maximbaz** [sayanarijit/xplr#249]
Launch xplr, and execue `FocusPath /full/path/to/xplr/tests`. On the first try, the cursor will stay on the first file/folder in the `xplr` dir, not on the `tests`. But then going back to home dir, and rerunning this command will correctly focus on the `tests` dir. Same with `FocusPathFromInput`.

**Comment by maximbaz** [comment]
Apologies for dup

**Comment by sayanarijit** [comment]
Couldn't reproduce this. Pls check if there's any async message before this. Async is where things get complicated.

**Comment by maximbaz** [comment]
Could you try with this config?

```
version = "0.14.0"

xplr.config.modes.builtin.default.key_bindings.on_key.z = {
    messages = {
        {
            FocusPath = "/home/maximbaz/xplr/tests",
        },
    },
}
```

I press `z` once and focus is on the wrong folder, press `z` again and it's all good.

**Comment by sayanarijit** [comment]
Hmm, this is an issue...

**Comment by maximbaz** [comment]
So you were right about async after all 😜
