### ISSUE TITLE
Improve error logs

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#252]
Many error logs are vague, i.e. they don't help us know and debug the actual cause. Not very helpful.

**Comment by dtomvan** [comment]
Yeah, to debug you config (they break when you try to import something that doesn't exist) you need to do `less $XPLR_PIPE_LOGS_OUT`, which returns all of the logs, including the luajit output. Also, if you make a layout with only logs, it will only give you 1 line of logs.

**Comment by Narayanbhat166** [comment]
Hi @sayanarijit @dtomvan, I would like to work on this issue, If this enhancement is still required.

**Comment by sayanarijit** [comment]
Hey @Narayanbhat166, thank you for showing interest, however I think we have improved the error logs significantly over the years, also fixing the error layout display issue mentioned above. So, this issue can be closed. Unless you find something that needs further improvement. In that case, pls reopen the issue.
