### ISSUE TITLE
Previewer problems

### ISSUE THREAD

**Issue by mrdgo** [sayanarijit/xplr#258]
First things first: great file explorer! :)

I followed your instructions to get [1] to work.

# Setup
I downloaded `~/.config/nnn/plugins/preview-tabbed`
Then I placed the setup function from [1] into `~/.config/xplr/init.lua` and call it with your proposed parameters.

By the way: where do I have to place the `nnn_preview_wrapper.lua` so xplr can load it? I tried `~/.config/xplr/lua/` but this didn't work.

# Error message
When I now try to activate the previewer `:p` - I get an error: `sh: line 1: /home/ME/.config/nnn/plugins/preview-tabbed: Permission denied`.
Also xplr crashes so hard, that I have to close the shell to terminate the process.

## Further information
Persmissions of the file:
    - owner: me
    - group: me
    - octal: 644

What am I missing?

[1] [Add support for fifo based previewer #229](https://github.com/sayanarijit/xplr/pull/229)

**Comment by sayanarijit** [comment]
>  - octal: 644

Here. Should be 755. Run `chmod +x <path>`.

**Comment by sayanarijit** [comment]
For the config, you can have a look at [here](https://github.com/sayanarijit/.files/tree/Linux/nixpkgs/files/xplr).

**Comment by sayanarijit** [comment]
>  Also xplr crashes so hard, that I have to close the shell to terminate the process.

This is the FIFO doing its job. Run `cat /tmp/xplr.fifo`.

**Comment by sayanarijit** [comment]
> package.path = os.getenv("HOME") .. '/.config/xplr/?/init.lua'

This is what loads the modules. You can redefine it to suit your own preference, until we have a standardized plugin system.

**Comment by mrdgo** [comment]
Thank you very much for the quick response!!
Okay 755 makes sense - noob error.

The previewing still isn't really usable because the terminal window looses focus when moving selection in xplr. So I everytime I move one entry up or down in xplr, I have to refocus the window to further interact with xplr.

**Comment by sayanarijit** [comment]
As per https://github.com/jarun/nnn/blob/master/plugins/preview-tabbed, you need `xdotool` (optional) to keep the focus.

**Comment by mrdgo** [comment]
Neither normally nor in brute force mode does it change anything.
But this is then a `preview-tabbed` issue, right?

**Comment by sayanarijit** [comment]
Hmm... Check if `nnn` works for you. If it does, `xplr` should also work.

**Comment by sayanarijit** [comment]
You can also try `preview-tui`.

**Comment by mrdgo** [comment]
Again thank you very much for your quick support.
This is neither an xplr nor an nnn issue - this is due to xmonad, which doesn't support `_NET_ACTIVE_WINDOW` by default.
I will try `preview-tui`, and if it doesn't do, I will try to make `_NET_ACTIVE_WINDOW` work :)
