### ISSUE TITLE
Add support for voidlinux

### ISSUE THREAD

**Issue by shubham-cpp** [sayanarijit/xplr#266]
Hi @sayanarijit, I have added support of xplr for voidlinux. Unfortunately I dont know how to contribute to github wiki. 
Hopefully this helps

Just want to add this line in Quickstart.md
```markdown
   - **Void Linux** users follow the **[void-templates setup](https://github.com/shubham-cpp/void-pkg-templates)** guide.
```

**Comment by sayanarijit** [comment]
Awesome! Thanks.

**Comment by sayanarijit** [comment]
Added to the Wiki. Closing this.
