### ISSUE TITLE
Global selection list

### ISSUE THREAD

**Issue by fedoranvar** [sayanarijit/xplr#267]
Good day to you!

Briefly search won't give a result, so i ask here:

Can multiple xplr-instances communicate with each other?

To be exactly, is it possible to select files in one instance and do selection-actions in another (similar to LF), sort of global selection list?

Thank you!

**Comment by sayanarijit** [comment]
Hey!

xplr sessions doesn't share state with each other, so there's no global selection list.
Tasks like simple copy-paste are done using the [global clipboard](https://github.com/sayanarijit/xplr/wiki/Hacks#copy--paste-using-system-clipboard).
But this can also be modified to write the selection to a temporary file, so that other xplr sessions can use the [SelectPath](https://docs.rs/xplr/latest/xplr/app/enum.ExternalMsg.html#variant.SelectPath) message to select paths from the file.

Let me know if this works for your use case.

**Comment by sayanarijit** [comment]
There's also `--on-load` CLI option that can be used to select paths on load.

**Comment by sayanarijit** [comment]
e.g. `xplr --on-load 'SelectPath: /home/sayanarijit'`

**Comment by fedoranvar** [comment]
it gives me some ideas, such as using temporary file for storing selections between instances and using it in some 'Global Selection Pane' and some keybinding to switch it with 'Local Selection Pane'

If something will come up, i'll post it here

Thank you!

**Comment by sayanarijit** [comment]
Hey @fedoranvar, I just published [alacritty.xplr](https://github.com/sayanarijit/alacritty.xplr), you can use it with [xclip.xplr](https://github.com/sayanarijit/xclip.xplr) to mimic the copy-paste experience with global selection list.

If you aren't using Alacritty or xclip, you can still see the concept and implement in your config.

**Comment by duganchen** [comment]
I think the use case for this is to get miller columns by opening two terminal split panes and a separate file manager instance in both. That's how lf and nnn do it.

Personally, I use bookmarks to cover that. Each per-session bookmark serves the same function as a tab in Ranger. Have a way to quickly jump between two directories, and you have the advantage of Miller columns.

The implementation I have is here:

https://github.com/duganchen/dirmarks/blob/main/dirmarks
https://github.com/duganchen/dotfiles/blob/main/cfg/.config/xplr/init.lua

The main thing I'm currently planning to add is to have " jump to the the last this-session-only bookmark that you added or jumped to. As it does in Ranger.

**Comment by sayanarijit** [comment]
For that use case, there's also dual-pane.xplr and context-switch.xplr...

More powerful with registers.xplr.

**Comment by sayanarijit** [comment]
https://xplr.dev/en/awesome-plugins
