### ISSUE TITLE
Opening xplr inside symlink changes to physical path

### ISSUE THREAD

**Issue by MithicSpirit** [sayanarijit/xplr#285]
If I open `xplr` inside a directory that is a symlink, like `/lib` on most Linux systems, `xplr` will instead open in the corresponding physical path (`/usr/lib` in the previous example). Opening a subdirectory of a symlink also has the same behavior (`/lib/gcc` will open in `/usr/lib/gcc`).
The weirdest part about this is that `xplr` does support opening symlinks, for example by opening `/` in `xplr` then pressing `l` on `/lib` will make the path `/lib` instead of `/usr/lib`.

**Comment by sayanarijit** [comment]
> If I open xplr inside a directory that is a symlink, like /lib on most Linux systems, xplr will instead open in the corresponding physical path (/usr/lib in the previous example). Opening a subdirectory of a symlink also has the same behavior (/lib/gcc will open in /usr/lib/gcc).

Thanks for reporting. We may be able to fix this, though.

> The weirdest part about this is that xplr does support opening symlinks, for example by opening / in xplr then pressing l on /lib will make the path /lib instead of /usr/lib.

Yes... This was fixed [in this pr](https://github.com/sayanarijit/xplr/pull/36). And [this pr](https://github.com/sayanarijit/xplr/pull/93) added support for following the actual path of the symlink.

**Comment by sayanarijit** [comment]
I was able to make `xprl $PWD` work. But, plain `xplr` still resolves the symlink.
