### ISSUE TITLE
How to BashExec in background? (&)

### ISSUE THREAD

**Issue by fedoranvar** [sayanarijit/xplr#291]
I'm trying to `dragon` selected files

```
xplr.config.modes.builtin.selection_ops.key_bindings.on_key["D"] = {
    help = "Drag&Drop",
    messages = {
      {
        BashExec = [===[
        dragon $(cat $XPLR_PIPE_SELECTION_OUT) > /dev/null 2>&1 &
        ]===]
      },
      "PopMode",
    },
}
```

But can't run it in background

Is there any workaround?

**Comment by sayanarijit** [comment]
Hi... I just published [dragon.xplr](https://github.com/sayanarijit/dragon.xplr). Hope this helps.

**Comment by sayanarijit** [comment]
BTW, as for your script, this should've worked, but there's some weird gotcha.

This works:

```bash
        FILES=$(cat ${XPLR_PIPE_SELECTION_OUT:?})
        ([ "$FILES" ] && dragon $FILES) &
```

So you'll need to cat the file, assign the value before spawning a background shell. Probably because of the environment variable. Great learning.

**Comment by sayanarijit** [comment]
Ah right.. just remembered, when we send process background, xplr might delete the file before the background process gets to access it.

**Comment by fedoranvar** [comment]
Thank you!
