### ISSUE TITLE
Native Windows Support

### ISSUE THREAD

**Issue by ghost** [sayanarijit/xplr#308]
error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\lib.rs:24:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^ maybe a missing crate `sys`?

error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\lib.rs:27:9
   |
27 | pub use sys::tty::{is_tty, get_tty};
   |         ^^^ maybe a missing crate `sys`?

error[E0433]: failed to resolve: maybe a missing crate `sys`?
 --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:5:5
  |
5 | use sys::tty::get_tty;
  |     ^^^ maybe a missing crate `sys`?

error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:28:5
   |
28 | use sys::attr::{get_terminal_attr, raw_terminal_attr, set_terminal_attr};
   |     ^^^ maybe a missing crate `sys`?

error[E0432]: unresolved import `sys`
  --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:29:5
   |
29 | use sys::Termios;
   |     ^^^ maybe a missing crate `sys`?

error[E0425]: cannot find function `get_tty` in this scope
  --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:14:36
   |
14 |     thread::spawn(move || for i in get_tty().unwrap().bytes() {
   |                                    ^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_tty` in this scope
  --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:43:36
   |
43 |     thread::spawn(move || for i in get_tty().unwrap().bytes() {
   |                                    ^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
  --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:45:9
   |
45 |         set_terminal_attr(&self.prev_ios).unwrap();
   |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_terminal_attr` in this scope
   --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:102:23
    |
102 |         let mut ios = get_terminal_attr()?;
    |                       ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `raw_terminal_attr` in this scope
   --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:105:9
    |
105 |         raw_terminal_attr(&mut ios);
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
   --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:107:9
    |
107 |         set_terminal_attr(&ios)?;
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
   --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:119:9
    |
119 |         set_terminal_attr(&self.prev_ios)?;
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_terminal_attr` in this scope
   --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:125:23
    |
125 |         let mut ios = get_terminal_attr()?;
    |                       ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `raw_terminal_attr` in this scope
   --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:126:9
    |
126 |         raw_terminal_attr(&mut ios);
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
   --> C:\Users\\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:127:9
    |
127 |         set_terminal_attr(&ios)?;
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to 15 previous errors

Some errors have detailed explanations: E0425, E0432, E0433.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `termion`

**Comment by sayanarijit** [comment]
Hey @CaptainMaps, unfortunately xplr doesn't currently have native support for windows since I don't have the infrastructure to develop and test it on windows machines. However, I heard xplr runs fine on WSL.
If there's enough interest in the windows community, I'd be happy to merge compatibility patches.

**Comment by CaptainMaps** [comment]
If I install WSL, would the command run perfectly? Or do I have to do something else to install it?

**Comment by sayanarijit** [comment]
It should run fine... Assuming you're using the ubuntu subsystem, you should be able to download the linux release and run directly. Or install using cargo.

**Comment by sayanarijit** [comment]
Hey @CaptainMaps, I hope you were able to run xplr in WSL. Please feel free to reopen if not.

**Comment by rashil2000** [comment]
Hi @sayanarijit 

I don't know what changed from the last time (did xplr switch from termion to crossterm?), but the compilation is successful now. 

![image](https://user-images.githubusercontent.com/46838874/129169871-ae7f7c75-154e-41db-a254-1faa51300ea3.png)

However it errors out when the binary is run. Would you mind keeping this issue open to track Windows support (from outside contributors)?

**Comment by sayanarijit** [comment]
Sure. I removed termion in https://github.com/sayanarijit/xplr/commit/f1e75caf895781ae872bc7173f96916b078f20e1 and copied only the part that xplr was using to read inputs, which is still windows incompatible.

Also, the default configuration currently assumes xplr is running on unix, and hence, depends on bash and many unix specific commands. So to make xplr run natively on windows, the default configuration file `init.lua` will need a lot of work too. And so does many other plugins. That's why I was encouraging running on WSL, but I understand that may not be what you want.

**Comment by rashil2000** [comment]
The issue with WSL is that it will only interact with WSL processes and files, accessing host files through `/mnt` is slow and not recommended. So a native solution would be better.

**Comment by sayanarijit** [comment]
I have renamed the issue to reflect its goal. I don't think there's an easy way to achieve this as xplr depends on unix commands to perform certain tasks. We'll have create and maintain a separate config file and plugin ecosystem specially for windows.

But I'm keeping this issue open in case anyone wants to go that route, or has some creative solution.

**Comment by CaptainMaps** [comment]
It worked fine with WSL. Kinda useless to me now though since I can open windows file explorer instantly now instead of waiting a minute each time.

**Comment by rashil2000** [comment]
WSL is just Linux. You don't need to do anything to make it work there.

For Windows on the other hand, it's a lot different story.

**Comment by CaptainMaps** [comment]
My point to use it was because my old laptop can't open the file explorer instantly. It takes a minute each time to open. What I was trying was to use a different file explorer that is faster than windows file explorer. Since I was learning rust, I wanted to test its speed. So I looked for a file manager that was made using rust and found this. I see it as pointless now since opening the windows file explorer is essentially instant on this new laptop.

For Linux, yeah, good.

But for Windows, maybe for old PCs.

**Comment by sayanarijit** [comment]
@CaptainMaps thanks for explaining your use case. Yes, xplr definitely isn't a suitable replacement for Windows explorer. Even in Linux or Mac, it isn't a suitable replacement for most file managers, depending on the use case. It solves a particular problem (of being insanely hackable) without compromising much on other aspects, such as speed and minimalism. Hence, as an example, it is suitable for people who prefer their tools being "programmable" over being "fast" or "batteries included".

**Comment by CaptainMaps** [comment]
@sayanarijit Maybe if it did have Windows support. It would be much more convenient to open it using just the terminal. Would be usable for some apps like VS Code too. Seeing as it has an integrated terminal.

**Comment by sayanarijit** [comment]
I'd say let's close this issue, since it has been open for a long time and no one seems very interested. If anyone is really interested in tackling this challenge, feel free to reopen it.
