### ISSUE TITLE
can't load C modules in safe mode

### ISSUE THREAD

**Issue by fhill2** [sayanarijit/xplr#309]
I'm experimenting with creating an .xplr plugin that runs a [msgpack nvim client](https://github.com/neovim/lua-client) and is able to send and receive data between nvim and xplr.

 
When I `require'luv'`, (dependency of the nvim lua client) safe mode is enabled in the Lua environment, so I am unable to require any C modules.

To workaround, this means I can use non C modules for the msgpack client in the .xplr plugin (which is possible but i'd rather avoid as there has been a lot of work done on the nvim lua client) 
or use [nvr](https://github.com/mhinz/neovim-remote) 

What are your thoughts behind disabling C modules in the lua environment? 
I believe a lua <-> lua msgpack would be great to have and to build on the work done at [nvim-client](https://github.com/neovim/lua-client) would be the best starting point.

**Comment by sayanarijit** [comment]
Wow nice idea... I'm using the mlua rust library which could be [blocking the unsafe c calls](https://github.com/khvzak/mlua#safety).

I also incline towards having safer bindings, but I agree it'd be nice to be able to reuse a mature library. However, I don't think enabling unsafe mode in the mlua library would be very easy.

I'd like to clarify that I'm very new to the Lua ecosystem, so I'll need to do some research and playing around before I can brainstorm a perfect solution.

Meanwhile, what do you think about using a Lua msgpack client and only implementing the parts that are required for the very specific plugin use case? I don't think there will be a lot api calls in the initial plugin implementation. It can grow slowly as the plugin matures.

**Comment by fhill2** [comment]
Yes that sounds like the way forward.
 I'll look at making it work without luv. I could most likely use [libmpack only](https://github.com/neovim/lua-client/blob/master/nvim/msgpack_rpc_stream.lua) and not the [Session class](https://github.com/neovim/lua-client/blob/master/nvim/session.lua) that controls it.
libmpack is non C.

**Comment by khvzak** [comment]
`mlua` supports loading C modules when created with [`Lua::unsafe_new()`](https://docs.rs/mlua/0.6.2/mlua/struct.Lua.html#method.unsafe_new)

In this mode it also enables `ffi` (luajit) and `debug` Lua modules.

**Comment by sayanarijit** [comment]
Wow nice... Thanks a lot.
