### ISSUE TITLE
focus_selection_ui style

### ISSUE THREAD

**Issue by fedoranvar** [sayanarijit/xplr#322]
Good day to you!

I have background colors for focus_ui and selection_ui

![image](https://user-images.githubusercontent.com/52028706/133097727-abba2aec-9ebb-4cdb-b6f4-71f0429476bd.png)

but when focus is on selection, then it gets hard to tell: item selected or not

![image](https://user-images.githubusercontent.com/52028706/133097314-a8783f07-e17d-453c-a536-0c9529900aa7.png)

is it possible to add focus_selection_ui style?

Thank you!

**Comment by sayanarijit** [comment]
Nice! Sure.

**Comment by sayanarijit** [comment]
@fedoranvar pls test & review #323 whenever possible.

**Comment by fedoranvar** [comment]
@sayanarijit got it. i've distrohoped from Void to NixOS, and need some time to configure environment.

I'll try it on this weekend

**Comment by fedoranvar** [comment]
![image](https://user-images.githubusercontent.com/52028706/134266451-4e441426-370f-4e56-9ecd-076423ebe4ce.png)
tested.

Looking good to me.

Thank you!

**Comment by sayanarijit** [comment]
Since it's a UI breaking change, I'll publish a major release by the end of this month or the first week of next month.
