### ISSUE TITLE
`deserialize error: recursive table detected`

### ISSUE THREAD

**Issue by ExpandingMan** [sayanarijit/xplr#332]
On running `xplr` I get only this error message.  This is on the tagged 0.14.7.

Runs fine on my Manjaro machines, on the Ubuntu machine I use for work I always get this error.  Doesn't seem to be tied to any particular directory.  I have tried it with no config file at all.

**Comment by sayanarijit** [comment]
Hi... I'm testing on a docker and the [direct download](https://xplr.dev/en/install#direct-download) option seems to work fine. Let me check compiling from the source.

**Comment by sayanarijit** [comment]
Yes, I confirm there's some issue is xplr is installed using `cargo install --force xplr`. Probably related to https://github.com/khvzak/mlua/issues/74.

**Comment by sayanarijit** [comment]
On the other hand, if I clone the repo, checkout `v0.14.7` and execute `cargo run --release`, it runs fine. Very weird.

**Comment by sayanarijit** [comment]
And then, even more weird, if I install using `cargo install --path . --force`, it fails.

**Comment by sayanarijit** [comment]
Upgrading mlua to `0.6.3` doesn't help.

**Comment by sayanarijit** [comment]
Damn if I reinstall xplr on my Manjaro using `cargo install --force xplr`, I get the same error!

**Comment by sayanarijit** [comment]
Ok, so, it should work fine if you pass `--locked`. i.e. `cargo install xplr --locked --force`. I'll update the docs and recommend to always use `--locked`.

There's some issue with mlua `0.6.3` and installing xplr without passing `--locked` installs that version of mlua.

**Comment by sayanarijit** [comment]
@maximbaz recommended this long ago. Not sure why I changed my mind :sweat_smile: .

**Comment by ExpandingMan** [comment]
Cool, thanks for your help.
