### ISSUE TITLE
Improve the homepage

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#340]
Let's improve [xplr.dev](https://xplr.dev) homepage by:

- Replace GIF with a cool demo video
- Use more icons than text.
- A nice mix of colors.
- A nice & clean look overall.

**Comment by zainulabideen1122** [comment]
Hi @sayanarijit, can you assign this issue to me? I am able to do this task.

**Comment by zainulabideen1122** [comment]
Do you have that demo video? or will I upload some random video?

**Comment by sayanarijit** [comment]
Existing ones are quite outdated. I think I'd be better to upload a new video. There are many terminal video recorder projects.

**Comment by sayanarijit** [comment]
you can place the video in resources directory.

**Comment by zainulabideen1122** [comment]
Yeah, I got it.

**Comment by zainulabideen1122** [comment]
and 1 last thing, I am using HTML, CSS, and js.

**Comment by sayanarijit** [comment]
I'd prefer to avoid js as much as possible, but if it adds real value to the homepage, sure 👍

**Comment by sayanarijit** [comment]
Hey @zainulabideen1122 please keep us posted on your progress.
Feel free to join our [discord](https://discord.gg/JmasSPCcz3) chat if you prefer chat over GH discussions.
You don't have to do everything at once. You can create several PRs dedicated to separate tasks for the homepage.

**Comment by zainulabideen1122** [comment]
Hy @sayanarijit, your website is almost complete. Only the demo video and some links are left.
