### ISSUE TITLE
Any way to overlay config (i.e. override only a small part of the config)?

### ISSUE THREAD

**Issue by tgharib** [sayanarijit/xplr#353]
I would like to override the `q` keybind in the default mode but I don't want to copy the entire configuration, as doing so will mean that I will have to maintain the configuration with any future [breaking changes](https://xplr.dev/en/upgrade-guide). I tried `xplr`'s `--extra-config` flag but `xplr` seems to ignore the default config when I do that.

The goal is to change this part of the config:

      ["q"] = {
        help = "quit",
        messages = { "Quit" },
      },

to

      ["q"] = {
        help = "quit",
        messages = { "PrintPwdAndQuit" },
      },

so that `cd on quit` works with my `.bashrc` function:

    x() {
      cd `xplr`
    }

**Comment by tgharib** [comment]
Ah, thanks for the example

**Comment by sayanarijit** [comment]
Also, try this: https://github.com/sayanarijit/xplr/pull/437
