### ISSUE TITLE
Better symlink support

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#37]
@maximbaz:

> would be nice to be able to show in the UI the destination of the symlink, and potentially also whether symlink leads to a directory or to a file (i.e. can be entered by pressing l).

**Comment by maximbaz** [comment]
I saw you have "sorting" in your TODO (🤞), so to add to the above, once it's possible to make xplr group folders first, it would also be very nice if symlinks pointing to directories would also be shown together with the directories.
