### ISSUE TITLE
`explore_recursive_async()` results are switched randomly.

### ISSUE THREAD

**Issue by sux2mfgj** [sayanarijit/xplr#372]
The function calls explore_async() and the explore_async() creates a thread and start to search the directory. As a result, the order of results are switched sometimes in recursive call.  

```
pub(crate) fn explore_recursive_async(...) {
    explore_async(...);
    if let Some(grand_parent) = parent.parent() {
        explore_recursive_async(...);
    }
}
```

Is this behavior as you expected?

**Comment by sayanarijit** [comment]
https://github.com/sayanarijit/xplr/issues/372#issuecomment-950313091 has been fixed.

And let's do the optimization as part of https://github.com/sayanarijit/xplr/issues/372.

I think this can be closed now.
