### ISSUE TITLE
Focused Node. Fields: date_modified, date_created, uid, guid

### ISSUE THREAD

**Issue by fedoranvar** [sayanarijit/xplr#379]
Good day to you!

Is it possible to access to `date_modified`, `date_created` and user-owner, and group-owner via LuaArgument?

(example of fields - exa)
![image](https://user-images.githubusercontent.com/52028706/138872126-099996fc-0b61-4774-8e75-1b15ca55dc61.png)

(example of fields - nnn)
![image](https://user-images.githubusercontent.com/52028706/138872303-7e467905-fc02-43e8-81bb-f3bc22c6d616.png)

Thinking of workaround like  getting file details by filepath with some Lua funcs, but i think these fields will be useful in xplr byitself,  if they don't exist in it.

I would like to access and print these fields in `CustomContent` pane
![image](https://user-images.githubusercontent.com/52028706/138872457-6488a8be-b5ec-46c9-b108-90f25cf7d55f.png)
```lua
xplr.fn.custom.status = function(ctx)
	local a = ctx.app
	-- ' - ' .. a.focused_node.asolute_path ..
	local status = ""
	status = status .. "\n" .. a.pwd
	if #a.selection > 0 then
		status = status .. "\n" .. "sel " .. tostring(#a.selection)
	end
	status = status .. "\n" .. a.directory_buffer.focus + 1 .. "/" .. a.directory_buffer.total
	status = status .. "\n" .. tostring(a.focused_node.human_size)
	-- status = status .. "\n" .. tostring(a.focused_node.relative_path)
	return status
end
```
Thank you!

**Comment by sayanarijit** [comment]
We have decided not to go with implementing datetime in #390 due to performance concerns. I'm not sure if displaying uid, gid would add much value.

Still, if performance is not a concern, it's possible to get those details via Lua and shell.

Example:

```lua
xplr.config.layouts.builtin.default = {
  Vertical = {
    config = {
      constraints = {
        { Percentage = 80 },
        { Percentage = 20 },
      },
    },
    splits = {
      "Table",
      {
        CustomContent = {
          title = "custom title",
          body = { DynamicParagraph = { render = "custom.render_layout" } },
        },
      },
    },
  },
}

xplr.fn.custom.render_layout = function(ctx)
  if ctx.app.focused_node then
    local p = io.popen("ls -ld '" .. ctx.app.focused_node.relative_path .. "'")
    local out = p:read("*a")
    p:close()
    return out
  else
    return ""
  end
end

```

Could be faster with a Lua module like `lfs` (I couldn't make it work with my limited Lua knowledge).

Hence, closing this issue. Feel free to reopen if any opinions.

**Comment by sayanarijit** [comment]
Actually made it work with the correct luarocks setup.

```lua
package.path = os.getenv("LUA_PATH") .. ";" .. package.path
package.cpath = os.getenv("LUA_CPATH") .. ";" .. package.cpath



local lfs = require("lfs")

xplr.config.layouts.builtin.default = {
  Vertical = {
    config = {
      constraints = {
        { Percentage = 80 },
        { Percentage = 20 },
      },
    },
    splits = {
      "Table",
      {
        CustomContent = {
          title = "custom title",
          body = { DynamicParagraph = { render = "custom.render_layout" } },
        },
      },
    },
  },
}

xplr.fn.custom.render_layout = function(ctx)
  local f = ctx.app.focused_node
  if f then
    local a = lfs.attributes(f.relative_path)
    return string.format(
      "%s %s:%s %s %s %s",
      a.permissions,
      a.uid,
      a.gid,
      f.human_size,
      a.access,
      f.relative_path
    )
  else
    return ""
  end
end

```
