### ISSUE TITLE
nnn's contexts

### ISSUE THREAD

**Issue by fedoranvar** [sayanarijit/xplr#380]
Good day to you!

I like nnn's contexts 
![image](https://user-images.githubusercontent.com/52028706/138873288-75ad184b-a75f-46a6-b910-7fb7928b646e.png)
 - it allows me to open file manager in root directory and do some stuff in it's subfolders (`fzcd`-plugin for example) 
 - i found it better then dual pane (ranger-llike) concept
 
 my question is:
 is there a way to achieve such functionality in xplr?
 and what's your thoughts about to integrate this in xplr (on rust)?
 
 Thank you!

**Comment by igorepst** [comment]
I wrote such a plugin: https://github.com/sayanarijit/xplr/discussions/404
