### ISSUE TITLE
macOS + arm64: Crashes with "PANIC: unprotected error in call to Lua API (7)"

### ISSUE THREAD

**Issue by jmechnich** [sayanarijit/xplr#384]
When opening xplr after a fresh installation, it (almost) always crashes instantly with:
`PANIC: unprotected error in call to Lua API (7)`.

Depending on the current working directory or if a user-local init.lua exists, it might take another key press for it to crash.

Version: 0.15.2
System: arm64 on macOS 12.0.1 installed using homebrew (both from a bottle and built from source)

**Comment by macintacos** [comment]
Hello! Just discovered the tool, been wanting to give it a test run, and unfortunately having it panic immediately is a pretty big blocker to me checking it out 😅 any idea when this fix will be released?

**Comment by jmechnich** [comment]
If you are using homebrew, you can `brew install xplr --HEAD`.

**Comment by sayanarijit** [comment]
Published https://github.com/sayanarijit/xplr/releases/tag/v0.16.0. It should be available in Homebrew stable channel soon.
