### ISSUE TITLE
Add a new column indicates time of last modification

### ISSUE THREAD

**Issue by sux2mfgj** [sayanarijit/xplr#390]
Related to #379.

Tasks for supporting the `time` column.
- [ ] implement rust backend
    - [ ] Node and NodeUiMetadata
    - [ ] init.lua
    - [ ] Sorter
    - [ ] Filter
- [ ] Update document

I think those tasks are needed to support the new column. If there are any tasks that are missing, let me know.

**Comment by sux2mfgj** [comment]
The PR #391 covered `Node` related implementation and `init.lua` updating.

**Comment by sayanarijit** [comment]
I think that's all. Though I'll check it properly soon. For now I provided initial feedback in the pr.

**Comment by sayanarijit** [comment]
Closing this WRT https://github.com/sayanarijit/xplr/pull/423
