### ISSUE TITLE
Focused_node and empty dir

### ISSUE THREAD

**Issue by igorepst** [sayanarijit/xplr#417]
Hi @sayanarijit.
It seems there are two separate issues that may be reproduced by the same way, but, perhaps, this is just something I don't understand.
Given the following init.lua and `xplr` 0.16.4:

```lua
version = '0.16.0'
xplr.config.modes.builtin.default.key_bindings.on_key['f4'] = { help = 'edit file', messages = { { CallLua = 'custom.edit_file' } } }
xplr.fn.custom.edit_file = function(a)
    os.execute('echo ' .. (a.focused_node and 'focused is NOT nil' or 'focused is nil') .. '>>/tmp/fn 2>&1')
    os.execute('echo ' .. a.focused_node.pwd .. '>>/tmp/fn 2>&1')
end
```
If you go to an **empty directory** and press 'F4', the following happens:
1. `/tmp/fn` is created with a string `focused is NOT nil`, although as the directory is empty, I would say that the `focused_node` should be `nil`. Documentation, at least from my point of view, suggests this is wrong, describing `focused_node` as `Type: nullable Node`. And at the same time the second `os.execute` throws exception that may be seen in logs
```
 ERROR   runtime error: [string "init"]:5: attempt to index field 'focused_node' (a userdata value)
stack traceback:
        [string "init"]:5: in function <[string "init"]:3>
```
suggesting that it is actually not a table, but a userdata.
2. At the same time the above exception produces log string that is actually cannot be seen in logs using the above almost default configuration. I mean I see this:
![image](https://user-images.githubusercontent.com/1630792/142484263-6bf53b33-540e-413a-8cac-534123d54ed9.png)
Here, probably, the first line of the error should be seen

Thanks!

**Comment by sayanarijit** [comment]
1. I'd use [this](https://stackoverflow.com/a/27028488) to print the table and io.read() to pause the execution after printing the table. This allows me to see what really happens.
2. There could be a new line character in the log which caused the empty line. We can probably strip it, but then also, we won't get much info if the log has multiple lines and the last line has onle 1 or 2 words. We'll need to type `:l` to see the whole log.

**Comment by igorepst** [comment]
Regarding logs, understood. I did the same thing, just thought it would be better to show the **first** line of each log entry and not the last one, if the view cannot present it fully.
Now, regarding `userdata`. The current situation causes issues, for ex., in your plugin `alacritty.xplr`, as the right line [here](https://github.com/sayanarijit/alacritty.xplr/blob/64c8ec58ac88425366f1207ffacfe9b15012ba08/src/init.lua#L45) should be
```
        if args.send_focus and type(app.focused_node) == 'table' then
...
```
otherwise, the same exception `attempt to index field 'focused_node' (a userdata value)` is thrown.
Here I should add that even though I have 17 years of professional experience in programming and I understand intuitively what the Rust code does when I read parts of it from your repo, it is tough as I don't know Rust at all and in the near future I won't find a time to dive deeper. So I think there are 2 options:
1. Potentially break backward compatibility and return `nil` [here](https://github.com/sayanarijit/xplr/blob/04dde7a477391e4deaba4f3b4e8526026fc98e81/src/app.rs#L2779), checking, perhaps, that `focused_node.pwd` is not `null`.
2. Document it, either for `focused_node` specifically or for [Node](https://xplr.dev/en/message#node) overall if it may happen in other places (I may do it and open a PR)

Thank you :)

**Comment by sayanarijit** [comment]
Ah thanks for the detailed explanation. This is definitely an issue. After some research, I found [Rust's `None` serialize into Lua `null`](https://github.com/khvzak/mlua/blob/204eedde3cbf93eb87a76848269238dadb2bd8e4/src/serde/ser.rs#L34-L42), which [represents an uninitialized variable name](https://stackoverflow.com/questions/31323443/lua-whats-the-difference-between-null-and-nil). It can be configured to be serialized into `nil` by setting `serialize_none_to_null` to `false`, but it's not the default for some reason.

However, I'm not sure why we get `userdata` instead of the variable `null` which should actually point to the value `nil`.

**Comment by sayanarijit** [comment]
Let's play around a bit.

1. Create a file named `x.lua` with the following code.

```lua
xplr.config.modes.builtin.default.key_bindings.on_key["#"] = {
  help = "edit file",
  messages = { { CallLua = "custom.edit_file" } },
}

xplr.fn.custom.edit_file = function(a)
  print(null)
  print(nil)
  print(a.unknown_field)
  print(a.focused_node)
  io.read()
end
```

2. Go to an empty directory, so that `a.focused_node` is `None`
3. Press `#`

We get the following result:

```lua
nil
nil
nil
userdata: NULL
```

I get `userdata: NULL` when I tried to pretty-print it.

I wasn't able to find any definition of `userdata: NULL`, so, I think it's some custom alternative to `null` which is different from `nil` in the sense that it isn't `undefined` (e.g. `a.unknown_field`). I guess that could be the intention behind `serialize_none_to_null` being set to `true` by default. Pinging @khvzak to confirm that it's indeed the case.

Anyway, I think for our use case, it makes sense to set `serialize_none_to_null` to `false` and use `nil` instead.

**Comment by igorepst** [comment]
As far as I understood the linked StackOverflow answer, from Lua's point of view, there is nothing special in `null`, it is just a regular valid variable name. As Lua doesn't require the variable to be declared before usage,
`v=null` is the same as `v=nil` if and only if `null==nil`, but
`null='bla'; v=null` will lead to `v='bla'`

**Comment by igorepst** [comment]
See pub trait LuaSerdeExt<'lua> at https://github.com/khvzak/mlua/blob/f0f5a8a0af62aff8007b20d58ef8f92b9ba8bc5d/src/serde/mod.rs#L17
Sorry for the formatting, I am writing from phone.
This expains the `userdata`

**Comment by sayanarijit** [comment]
> As far as I understood the linked StackOverflow answer, from Lua's point of view, there is nothing special in `null`, it is just a regular valid variable name. As Lua doesn't require the variable to be declared before usage, `v=null` is the same as `v=nil` if and only if `null==nil`, but `null='bla'; v=null` will lead to `v='bla'`

Yes, that's what I mentioned, there's no concept of `null` in Lua, But maybe the serialization library needed an alternative to `None` and that's why a custom `userdata: NONE` was implemented. I'm not sure though. But yes, it's easy to fix. We only need to set an option.

**Comment by sayanarijit** [comment]
> But yes, it's easy to fix. We only need to set an option.

Probably not.

**Comment by sayanarijit** [comment]
Ok fixed. I guessed right.

```
nil
nil
nil
nil
```

**Comment by khvzak** [comment]
`null` (lightuserdata 0x0 pointer) is an alternative to `nil` to keep fields in a table after serializing Rust structs with optional fields to Lua value.

Same as `null` in [lua-cjson](https://kyne.com.au/~mark/software/lua-cjson-manual.html#_null)
> Lua CJSON decodes JSON null as a Lua lightuserdata NULL pointer. cjson.null is provided for comparison.

It used by default to get the same result when applying `lua.from_value(lua.to_value(val)?)?` transformation.

**Comment by sayanarijit** [comment]
Got it. Thanks.
