### ISSUE TITLE
Add a "duplicate as" option

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#434]
A combination of copy and rename.
When we want to copy a file in the same directory with a different name, we need to go through a lot of steps.
Let's fix that.

**Comment by sayanarijit** [comment]
I'd suggest `D` key to do that, but no strong opinion.

**Comment by dtomvan** [comment]
As in, give the user an input buffer?

**Comment by sayanarijit** [comment]
Correct

**Comment by sayanarijit** [comment]
I really need it urgent. So, I'm taking over :)
