### ISSUE TITLE
would this be a possible alternative to lua for configuration?

### ISSUE THREAD

**Issue by erikLundstedt** [sayanarijit/xplr#442]
https://git.sr.ht/~ioiojo/include-fnl

fennel is a lisp dialect that "compiles*" to lua

> *compiles in the same way as less-css,sass and scss "compiles" to css

**Comment by sayanarijit** [comment]
Found a good introduction video: https://youtu.be/VC1DhAoRSpg

**Comment by sayanarijit** [comment]
As per the video, it should be pretty easy to write xplr config in fennel, without built-in support. All it takes is the fennel compiler and a Makefile in the config/plugin directory.

**Comment by dtomvan** [comment]
Staying in the sass<->css example, sass has some advantages over css. What kind of advantage do you get out of using fennel over lua? Or is it just that people like writing lispy code?

**Comment by sayanarijit** [comment]
I think it has been sorted.

To add fennel support, use the following steps:

- Get the `fennel.lua` library. You can get this from a [release tarball](https://fennel-lang.org/downloads/fennel-1.1.0.tar.gz) or by running make in a source checkout.
- Add `fennel.lua` to `~/.config/xplr/plugins/fennel.lua`.
- Add the following lines to `~/.config/xplr/init.lua`.

```lua
local home = os.getenv("HOME")

-- Lua search path
package.path = home
  .. "/.config/xplr/plugins/?/init.lua;"
  .. home
  .. "/.config/xplr/plugins/?.lua;"
  .. package.path

local fennel = require("fennel")

-- Fennel search path
fennel.path = fennel.path
  .. ";"
  .. home
  .. "/.config/xplr/plugins/?/init.fnl;"
  .. home
  .. "/.config/xplr/plugins/?.fnl;"

table.insert(package.loaders or package.searchers, fennel.searcher)
```
