### ISSUE TITLE
Feature add regular  express support for filtering

### ISSUE THREAD

**Issue by topelinux** [sayanarijit/xplr#473]
it would be very convenient for user to filter the wanted filename with regular express support e.g filter all the file with digital number(\d) in it.

**Comment by sayanarijit** [comment]
If possible, pls review https://github.com/sayanarijit/xplr/pull/474

**Comment by sayanarijit** [comment]
Implemented in https://github.com/sayanarijit/xplr/pull/474

**Comment by topelinux** [comment]
Thanks!!
