### ISSUE TITLE
Help fixing the error with the global version definition?

### ISSUE THREAD

**Issue by morphykuffour** [sayanarijit/xplr#479]
![image](https://user-images.githubusercontent.com/23323356/169694261-daf02bb4-ac30-47f4-9f2b-1640f92befa6.png)

**Comment by sayanarijit** [comment]
Add `version = "0.18.0"`. See https://xplr.dev/en/post-install

**Comment by sayanarijit** [comment]
TODO: Improve the error.

```
ERROR | Add `version = "{version}"` in /path/to/init.lua
```
