### ISSUE TITLE
Add cmd mode/repl mode support

### ISSUE THREAD

**Issue by topelinux** [sayanarijit/xplr#489]
Do you think an repl mode or command mode is need for get the inner state of xplr??
e.g to dump the information of `xplr.config.node_types.directory.meta`

thanks
Tope

**Comment by sayanarijit** [comment]
https://xplr.dev/en/messages#debugging

**Comment by sayanarijit** [comment]
Another thing I do is dump the lua table and call io.read() to stop the execution untill I press enter.

**Comment by sayanarijit** [comment]
Hopefully it's answered. Closing this.
