### ISSUE TITLE
Implement SearchFuzzy to replace filtered search

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#496]
Filtered search works well for basic use cases, but there's no way to sort the results based on how close they are to the search input. Adding the functionality will add some complexity and a Rust dependency. It also needs to play nice with the filters and sorters.

It's possible to [integrate xplr with tools like fzf](https://github.com/sayanarijit/fzf.xplr) to work around the limitation.

However, since xplr claims to be intuitive, should it default to the more intuitive fuzzy search? Or should it just stay stupid, simple and depend on external tools for the complex stuff, like it already does?

**Comment by roland-rollo** [comment]
+1 for first option: adding fuzzy search.

**Comment by Creator54** [comment]
> +1 for first option: adding fuzzy search.

+1

**Comment by sayanarijit** [comment]
I came up with this implementations: https://github.com/sayanarijit/xplr/pull/511

Looking for review/feedback.
