### ISSUE TITLE
Possible bug with filter using --on-load

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#503]
Tried: 
```
xplr --on-load 'AddNodeFilter: { filter: RelativePathDoesMatchRegex, input: ".*\\.png$" }' --on-load 'ExplorePwd'
xplr --on-load 'AddNodeFilter: { filter: RelativePathDoesMatchRegex, input: ".*\\.png$" }' --on-load 'Refresh'
```

Reported by @dtomvan

**Comment by sayanarijit** [comment]
Seems to be random. Sometimes works fine.

**Comment by sayanarijit** [comment]
Refresh doesn't work though.

**Comment by sayanarijit** [comment]
But the actual command would be...

```
xplr --on-load 'AddNodeFilter: { filter: RelativePathDoesMatchRegex, input: "\\.png$" }' --on-load 'ExplorePwd'
```

Still doesn't exactly do what it does when the filter is applied interactively.

**Comment by dtomvan** [comment]
> But the actual command would be...
> 
> ```
> xplr --on-load 'AddNodeFilter: { filter: RelativePathDoesMatchRegex, input: "\\.png$" }' --on-load 'ExplorePwd'
> ```
Hmm, it worked with `fr.*\.png$<enter><esc>` so I don't see why it would make any difference, it is shorter though.

`explorer::explore_sync` is called when doing `ExplorePwd`. I would guess the redraw is inconsistent, as filters are being applied in that function. Doing both `ExplorePwd` and `Refresh` should fix it. If not, the --on-load arguments may not be executed in order.

**Comment by dtomvan** [comment]
Same thing applies with:
```
echo 'AddNodeFilter: { filter: RelativePathDoesMatchRegex, input: "\\.png$" }' >> $XPLR_PIPE_MSG_IN
```
from inside xplr. This seemingly applies the filter, but it leaves the user with no directory nodes, as the faulty filter seems to not match anything. Clearing the filter afterwards and using the TUI to apply it manually seems to "fix" the filter, even tho the string representation `"rel=/\.png$"` is the same in all 3 cases.

**Comment by sayanarijit** [comment]
This seem to happen with only regex. Other filters are working fine.

```
xplr --on-load 'AddNodeFilter: { filter: RelativePathDoesEndWith, input: ".png" }' 'ExplorePwd'
```

**Comment by sayanarijit** [comment]
Ah... got it.

**Comment by sayanarijit** [comment]
It seems there's still some task scheduling issue. Running the following command in my homedir doesn't apply the filters. Looks like `ExplorePwd` happens before the filter is added.

```
xplr --on-load 'AddNodeFilter: { filter: RelativePathDoesEndWith, input: foo }' ExplorePwd
```

**Comment by sayanarijit** [comment]
I think it's because the explore_pwd_async() that sets the parent directory locations, also overrides the results for the pwd.
