### ISSUE TITLE
Crash in startup

### ISSUE THREAD

**Issue by i3d** [sayanarijit/xplr#513]
Here is the crash stacktrace

```
[2022-10-06 20:35:14.409429 -07:00] ERROR   runtime error: [string "init"]:23: attempt to index field 'cursor' (a nil value)                                              
  stack traceback:    
          [C]: in function '__newindex'    
          [string "init"]:23: in main chunk 
```

**Comment by sayanarijit** [comment]
Hi, `` was deprecated in `https://github.com/sayanarijit/xplr/releases/tag/v0.16.3`. See the [Upgrade Guide](https://xplr.dev/en/upgrade-guide).

**Comment by dtomvan** [comment]
I don't know if it's possible in mlua, but maybe it is useful to just ignore/warn the user when `__newindex` gets triggered instead of error and abort loading the rest of the config.

**Comment by sayanarijit** [comment]
It's not easy to do here, also we probably shouldn't do this. This is harmless in this particular case, but in other parts of the config, where a critical puece of code depends on a field, this might create unexpected errors.

**Comment by sayanarijit** [comment]
Anyway, hope this was resolved. Closing this.
