### ISSUE TITLE
[Discuss] Implement and expose xplr.util

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#517]
This table will contain handy utility functions such as ls(), dirname(), execute(), escape(), quote(), etc. This will make it easy to safely perform filesystem operations.

**Comment by sayanarijit** [comment]
This will bring some convenience, but will increase the learning curve, which is already significant for a file explorer.

**Comment by erikLundstedt** [comment]
> This will bring some convenience, but will increase the learning curve, which is already hard enough for a file explorer.

I think it would greatly simplify a lot of code and thus ease the learning curve

**Comment by roland-rollo** [comment]
I think it's  a good idea.
