### ISSUE TITLE
Cant preview files with :p 

### ISSUE THREAD

**Issue by luccahuguet** [sayanarijit/xplr#521]
I would like to preview files (specially text files) and read somewhere in the documentation that it could be done with :p but that option does not seem to exist.

Also congrats on the beautiful, and intuitive project

**Comment by sayanarijit** [comment]
Hi, you need to setup [preview-tabbed.xplr](https://github.com/sayanarijit/preview-tabbed.xplr) (all files) or see [tri-pane.xplr](https://github.com/sayanarijit/tri-pane.xplr) (text only).

**Comment by sayanarijit** [comment]
Hope this works. Closing this.
