### ISSUE TITLE
The screen is not cleared when launching from the console

### ISSUE THREAD

**Issue by dimitris-triantafyllidis** [sayanarijit/xplr#528]
I do not have much to add to the title.

To reproduce, switch to some tty, print several lines, launch xplr and you should see cells that should be empty containing output from the previous screen.

I am using xplr 0.20.0 on Arch Linux, installed with pacman.

**Comment by sayanarijit** [comment]
Hi, thanks for reporting. Could you please provide an example of the full command you're trying to run? i.e. the usecase for running xplr in tty...

**Comment by dimitris-triantafyllidis** [comment]
I do not have any specific use case in mind for running xplr in a tty. I ran xplr basically by accident after having quit htop and noticed this.

**Comment by sayanarijit** [comment]
I wasn't able to reproduce the issue in Manjaro and wezterm. Opening xplr after quitting htop works fine me.

**Comment by dimitris-triantafyllidis** [comment]
This only happens in a tty, not in X or Wayland. I should have clarified this.

**Comment by sayanarijit** [comment]
Ah right.. I thought spawning htop and then xplr was somehow causing it to open a tty.

For now, the quick fix would be to manually refreshing the screen using "ctrl-r", or use a `on_load` hook (see the docs) or alias xplr="xplr --on-load Refresh".

Will try to address this in the next release.

**Comment by dimitris-triantafyllidis** [comment]
Thanks for the workaround. I will leave it to you to close the issue whenever you see fit.

I haven't looked at the docs yet but this looks like a very nice project, thank you!

**Comment by sayanarijit** [comment]
Issue fixed by [this commit](https://github.com/sayanarijit/xplr/commit/053615b0415caae1159297718223f2a3b46a3827#diff-68c6f449503a33c74a15800c0a9c8fd34028465a06edcac92b32bbb9db64bbceR326). Closing this.
