### ISSUE TITLE
Equivalent message to `--print-pwd-as-result` option ?

### ISSUE THREAD

**Issue by PhML** [sayanarijit/xplr#534]
I have configured the following mapping:
```lua
xplr.config.modes.builtin.default.key_bindings.on_key["ctrl-enter"] = {
  help = "PrintPwdAndQuit",
  messages = {"PrintPwdAndQuit"}
}
```
Expecting that it would output the same as typing `Enter` with `xplr` launched with `--print-pwd-as-result` option but it does not.

I use the `0.20.0` version.

**Comment by sayanarijit** [comment]
Hi, seems like ctrl-enter (also shift-enter) isn't a valid terminal key.

You can use https://xplr.dev/en/debug-key-bindings to check what keys are supported.

**Comment by PhML** [comment]
Indeed, by replacing it by `ctrl-q` makes it work !
Thank you.
