### ISSUE TITLE
"Key map not found"  - Plugin key maps not working

### ISSUE THREAD

**Issue by richardhttps** [sayanarijit/xplr#543]
```
require('fzf').setup {
	mode = 'default',
	key = 'ctrl-f',
	args = "--preview 'pistol {}'",
}
```

```
require("zoxide").setup{
  mode = "default",
  key = "Z",
}
``` 
I have these lines in my init, but the keys aren't working.
I noticed this happens only with keys that are in `mode = "default"`. However, they do work If I move them from "default" to some other existing mode i.e `mode = 'delete'`.

[init.lua](https://pastebin.com/raw/NMZLqtQf)

**Comment by sayanarijit** [comment]
Hi, I see you have set `xplr.config.general.read_only = true`. Remove this line, or set it to `false` to fix this. This line prevents xplr from executing external commands. Feel free to reopen if issue is still there.
