### ISSUE TITLE
Allow using $LS_COLORS for theming

### ISSUE THREAD

**Issue by noahmayr** [sayanarijit/xplr#562]
I'm currently trying to get exa (https://github.com/ogham/exa) and xplr to show files and directory colors the same way.
I will most likely write a small integration calling lscolors (https://github.com/sharkdp/lscolors) in the column renderer for now, but since it's a rust library it seems like it might more sense to integrate this directly into xplr and allowing the user to enable it as a baseline with the possibility to override it for certain nodes. 
I've also noticed that xplr detects different mime types than exa and `file --mime-type <something>`, at least on MacOS.

**Comment by sayanarijit** [comment]
The way xplr ui exposes the api, it'd be difficult rendering colors in rust side. I think it should be an external lua plugin. Something like:
- https://github.com/prncss-xyz/icons.xplr
- https://github.com/dtomvan/extra-icons.xplr

**Comment by sayanarijit** [comment]
Reg mime type, we can definitely experiment and improve it.

**Comment by noahmayr** [comment]
Regarding the lscolors integration. While it is possible to do in lua, my current implementation requires getting the colored path and then parsing it to extract the actual ansi escapes so I can apply them not just to the path but also the icon. Integrating the library directly in rust would allow you to take their style type https://github.com/sharkdp/lscolors/blob/master/src/style.rs and map it to the xplr style. Then you could allow getting get the lscolors style with something like `xplr.util.lscolor(path)` and then with the util function `xplr.util.style` from https://github.com/sayanarijit/xplr/issues/564 it'd be possible to apply it to any string.

**Comment by sayanarijit** [comment]
This sounds interesting... Let's try it 👍

**Comment by noahmayr** [comment]
Closing this as the functionality was merged into `dev` with #569
