### ISSUE TITLE
Allow filtering file table based on list of absolute paths

### ISSUE THREAD

**Issue by noahmayr** [sayanarijit/xplr#584]
I would like to add fzf filtering directly in the table view instead of the way it's currently done in https://github.com/sayanarijit/fzf.xplr. Since fzf can be used non interactively to just return a list of matching entries, it could be used for fuzzily searching the current directory. 

The only thing close to allowing that right now is the `AbsolutePathIs` filter, but I see two problems with that:
1. At least a different filter type would be required that can take not just a single path, but a table containing a list of paths. Since adding two or more `AbsolutePathIs` filters results in an empty table
2. Even when adding that filter, I would want to do this while respecting all other filtering and sorting settings the user has currently applied and go back to those settings when popping the fzf filter mode. (Potentially doable with `RemoveLastNodeFilter`, but it might help to have some way of storing the current filter/sort config to be able to later restore it again)

**Comment by sayanarijit** [comment]
I think we can add fuzzy filtering using the skim integration. Instead of list of paths, it can take string input. The search already does that. However, unlike search, no sorting will be applied.

Will it be enough for your usecase?

**Comment by noahmayr** [comment]
My bad, I actually didn't realize that the default algorithm was already a fuzzy search...

I think it could still be useful to allow custom filtering (/searching) or sorting operations, in the case of fzf I'm especially interested in being able to use the same search syntax I use everywhere else (https://github.com/junegunn/fzf#search-syntax) but still have the built in table view display my results.

**Comment by sayanarijit** [comment]
It should already work with skim. See https://github.com/lotabout/skim#search-syntax

**Comment by sayanarijit** [comment]
We can probably add options to customize the skim matcher by adding more `xplr.general.search.*` fields. But I never felt the need to do so. Ofcourse, feel free to add them if it's useful to you.

**Comment by sayanarijit** [comment]
> It should already work with skim. See https://github.com/lotabout/skim#search-syntax

Actually it doesn't. Probably something to improve.

**Comment by noahmayr** [comment]
As far as I can tell the fuzzy-matcher package doesn't support this syntax, I'll try and see if we can use skim directly instead.

**Comment by noahmayr** [comment]
https://github.com/lotabout/skim/blob/master/src/engine/factory.rs#L53 this seems to be what I'm looking for
