### ISSUE TITLE
Set node_type for executable?

### ISSUE THREAD

**Issue by nosvagor** [sayanarijit/xplr#590]
I am having an issue setting the icon/style of files that are simple binaries. 

I see the [extra-icons plugin](https://github.com/dtomvan/extra-icons.xplr/blob/main/init.lua) has this in its custom function that appears to do this:
```lua
....
  local is_binary = m.permissions.user_execute
        or m.permissions.group_execute
        or m.permissions.other_execute

        if m.is_broken then
            -- Broken symlink icon is hardcoded. Not implemented in xplr yet.
            m.meta.icon = ""
        end

        if not m.is_broken and type(icon) ~= "string" and is_binary and m.canonical.is_file then
            m.meta.icon = icons["application/octet-stream"]
        end
....
```

I've tried setting `application/x-shellscript`, or `application/x-pie-executable` under mime_essence, but these don't seem to apply if the file does not have an extension.

any tips to getting this to work? Could it be simple to add an extra node_type for executables?

**Comment by sayanarijit** [comment]
We can maybe implement a custom module for checking mimetype based on the Node object. The mime_essense dependency can't handle directory as well, so we're setting inode/directory explicitly. In the custom mime_essense module we can implement all these checks.

**Comment by sayanarijit** [comment]
Is will try to return the mime type based on the node properties, then finally fall back to the actual mime_essense crate.
