### ISSUE TITLE
enter not working when create file

### ISSUE THREAD

**Issue by NavePnow** [sayanarijit/xplr#594]
When I want to create files using :c f command and then type enter, xplr has no response.

platform: macOS
version: 0.20.2
install via homebrew

**Comment by sayanarijit** [comment]
Hi, make sure you have the latest [gnu core utils](https://formulae.brew.sh/formula/coreutils) installed.

**Comment by sayanarijit** [comment]
Else this line will fail: https://github.com/sayanarijit/xplr/blob/59279b816dedeb42682cb288c25d1cf3d1f1be61/src/init.lua#L1554

**Comment by NavePnow** [comment]
> Hi, make sure you have the latest [gnu core utils](https://formulae.brew.sh/formula/coreutils) installed.

I installed the latest coreutils via homebrew, which is mentioned on the manual page. Should I debug or do something else?

**Comment by NavePnow** [comment]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/39482599/219850503-3f65a3b5-a39a-4d51-8078-3966731a1a3e.png">

**Comment by NavePnow** [comment]
btw, I check the path of realpath and [stackoverflow](https://apple.stackexchange.com/questions/450035/is-the-unix-realpath-command-distributed-with-macos-ventura), macOS has builtin realpath.

**Comment by sayanarijit** [comment]
Mac's built-in realpath is outdated. You need to set the PATH variable in your .bashrc or .zshrc after installing the latest coreutils. Follow the message after (re)installing coreutils.

**Comment by NavePnow** [comment]
after installing, homebrew said 
```
Commands also provided by macOS and the commands dir, dircolors, vdir have been installed with the prefix "g".
If you need to use these commands with their normal names, you can add a "gnubin" directory to your PATH with:
  PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
```
so currently macOS users could use `grealpath` instead of `realpath` to execute the commands.

<img width="219" alt="image" src="https://user-images.githubusercontent.com/39482599/219853171-b1f5691d-3f5d-4e16-8d7a-bb2e3c21c3f7.png">

could we make softlink for realpath or make pr to modify commands in rust file.

**Comment by sayanarijit** [comment]
The best way is to add `export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"` in your .bashrc or .zshrc.

To create the softlinks, you'll need to replace the built-in commands which could break macos. Modifying the commands to add prefix `g` isn't a good way, since it will break on Linux, while the issue is caused by outdated macos binaries. One thing we can do is, if the realpath command fails, fall back to just `touch`.

**Comment by NavePnow** [comment]
problem solved! thanks!
