### ISSUE TITLE
Image viewer (imv)

### ISSUE THREAD

**Issue by MitaiDart** [sayanarijit/xplr#607]
![image](https://user-images.githubusercontent.com/104931116/229995730-3b3c078d-671e-40c7-bf07-fa99da2b8319.png)
![image](https://user-images.githubusercontent.com/104931116/229995815-d0cb9dfd-b27d-47f4-bce4-ab9fea28fd16.png)

**Comment by sayanarijit** [comment]
Looks like lua syntax error. Remove the comma at line no. 3033.

**Comment by MitaiDart** [comment]
yes indeed, thank you, but how to view the pictures? here I am in the catalog with pictures but there is no image
![image](https://user-images.githubusercontent.com/104931116/230082564-44a77af8-450c-4925-84c7-b00550aa4e23.png)

**Comment by sayanarijit** [comment]
Pressed `P`?

**Comment by MitaiDart** [comment]
> Pressed `P`?

yes `14:40:08|WARNING) key map not found.`

**Comment by MitaiDart** [comment]
bro?

**Comment by sayanarijit** [comment]
I can't reproduce the issue. Pls post your full config here, or in a pastebin and share the link.

Also, run the following command (required `yq`):

```
xplr --on-load PrintAppStateAndQuit | yq -y .config.modes.builtin.default.key_bindings.on_key.P
```

**Comment by MitaiDart** [comment]
> xplr --on-load PrintAppStateAndQuit | yq -y .config.modes.builtin.default.key_bindings.on_key.P

```$ xplr --on-load PrintAppStateAndQuit | yq -y .config.modes.builtin.default.key_bindings.on_key.P
null
...```
[config](https://pastebin.com/ZTniHM4N)

**Comment by sayanarijit** [comment]
Also, basic Lua thing. The return statement should be at the end, else the later part of the code won't be executed.

**Comment by MitaiDart** [comment]
Thanks it's work!

**Comment by lucasjinreal** [comment]
How to preview image by default?
