### ISSUE TITLE
Implement tabs and/or panes

### ISSUE THREAD

**Issue by sayanarijit** [sayanarijit/xplr#61]

**Comment by sayanarijit** [comment]
Closing this as I have decided xplr won't have native tabs and panes. However, I'll keep experimenting integrating xplr with tools that provide tabs and panes support (e,g, https://github.com/zellij-org/zellij).

**Comment by mharrisb1** [comment]
@sayanarijit did you ever find a good workflow with xplr + zellij?

**Comment by sayanarijit** [comment]
I don’t use zellij as of yet. But there are people who seems to be using zellij with xplr and other file explorers. For instance this example with yazi https://github.com/helix-editor/helix/discussions/8314#discussioncomment-7027441

there’s also https://github.com/igorepst/term.xplr which has tmux integration, so I think it should also be able to integrate zellij.
