### ISSUE TITLE
Broken icons

### ISSUE THREAD

**Issue by reagle** [sayanarijit/xplr#637]
Just heard of this and gave it my first try and see the icons are broken.

xplr 0.21.2
iterm2 3.4.19
macOS 13.4.1 22F82 arm64

<img width="230" alt="SCR-20230630-lpfl" src="https://github.com/sayanarijit/xplr/assets/596814/8243878b-2441-4c76-b3fa-b6515540803c">

**Comment by sayanarijit** [comment]
Hi. Icons aren't built-in. These are just placeholders.

Try any of the icons plugin from this list:

https://github.com/sayanarijit/xplr/blob/dev/docs/en/src/awesome-plugins.md#theme

**Comment by reagle** [comment]
I followed the directions for [material-landscape](https://github.com/sayanarijit/material-landscape.xplr) and get an error:

```
13:28:01|ERROR) 'version' must be defined globally in /Users...
```

**Comment by sayanarijit** [comment]
Right... You need to define the version in the config file for compatibility check. See

https://github.com/sayanarijit/xplr/blob/dev/docs/en/src/post-install.md#create-the-customizable-config-file

**Comment by reagle** [comment]
Okay, so that error goes away, but I don't think my icon install worked. I suggest an app should be able to work as shown in screenshots upon install. (Couldn't you use unicode for initial icons?) I'm going to put this aside for now.

**Comment by sayanarijit** [comment]
Thanks for the feedback. Will update the demo when I get some time. As for unicode icons, it's difficult to find something that works on most systems and in most terminals, without special configuration. PRs are welcome BTW.

**Comment by sayanarijit** [comment]
You can join the discord/matrix if you need help. People are nice there. Closing this for now.
