### ISSUE TITLE
style being ignored

### ISSUE THREAD

**Issue by JosefLitos** [sayanarijit/xplr#640]
I tried to customize the colors to match my NvimTree looks, but it seems that some options ignore their style setting.

try:
```lua
xplr.config.general.selection.item.style = {fg = "Magenta", add_modifiers = {"Underlined"}}
xplr.config.general.table.row.style = {fg = "Magenta"}
xplr.config.general.table.row.cols = {
	{format = "builtin.fmt_general_table_row_cols_1", style = {fg = "Magenta"}},
	{format = "builtin.fmt_general_table_row_cols_0", style = {fg = "Magenta"}},
}
xplr.config.general.table.header.cols = {{format = "│", style = {fg = "Magenta"}}}
xplr.config.general.table.tree = {
	{format = "│", style = {fg = "Magenta"}},
	{format = "│", style = {fg = "Magenta"}},
	{format = "└", style = {fg = "Magenta"}},
}

```

**Comment by sayanarijit** [comment]
For files, LS_COLORS and the style defined in xplr config.node_types will override ui style.

**Comment by JosefLitos** [comment]
I haven't changed anything in the `node_types` section, though. The defaults look to me as nothing special is being set. Although I am not sure if that is what you meant, or if that was just file specific. Also, what does `file` refer to - filename being displayed?

**Comment by sayanarijit** [comment]
Right... If you can post a screenshot marking the regions with issue, would be great for debugging.

**Comment by sayanarijit** [comment]
Pushed some fixes to https://github.com/sayanarijit/xplr/commit/d01b6f0cd4bc380836958ddef91d74705e4ea7e5, though, I'm not sure if this will fix everything. Since the priority for these styles are lower than per file specific style ($LS_COLORS and node_types).

**Comment by JosefLitos** [comment]
It should be obvious when you apply the provided configuration - nothing is magenta although multiple things should be.

I added "Underline" to the selection to emphasize that it truly ignores the entire style table. Anyway, here is the picture:

![image](https://github.com/sayanarijit/xplr/assets/54900518/06cd666b-0a9c-4f8a-a139-0470bf49b628)

**Comment by sayanarijit** [comment]
Try [these changes](https://github.com/sayanarijit/xplr/commit/d01b6f0cd4bc380836958ddef91d74705e4ea7e5) with
```
LS_COLORS="" xplr -C styles.lua
```

**Comment by sayanarijit** [comment]
Pushed another fix: https://github.com/sayanarijit/xplr/commit/f440b56fe6a1f9bee72cc97cbc879477e95554d7

**Comment by JosefLitos** [comment]
Everything works with latest commit, except the `table.tree` styles. (I updated the config to include those too a little later)

**Comment by sayanarijit** [comment]
Good point. Let's see how to do it.

**Comment by sayanarijit** [comment]
BTW, we're going to port the default Lua functions to the Rust side as built-in defaults for performance. So, let's wait for the new implementation.

**Comment by JosefLitos** [comment]
Sounds great. Thanks for the quick responses.

**Comment by sayanarijit** [comment]
Closing this wrt https://github.com/sayanarijit/xplr/issues/641
