### ISSUE TITLE
Illegal format character q

### ISSUE THREAD

**Issue by duganchen** [sayanarijit/xplr#652]
I'm running XPLR in FISH, on my Mac, and when I "dD" to delete a directory, I see:

```
printf: illegal format character q

Permanently delete these files? [Y/n]:
```

My Mac has a /usr/bin/printf, and it's clearly what's being executed:

```
❯ /usr/bin/printf "%q", "aaa"
printf: illegal format character q
```

My Mac also has a /usr/bin/gls, which supports "%q", and yes, FISH has a built-in printf as well. But I think the expected behavior is for BASH's built-in printf to be used?

**Comment by sayanarijit** [comment]
Right... Bash should execute the command, even if your default shell is fish. Unless fish is named bash...

**Comment by sayanarijit** [comment]
And right, bash's built-in function should execute. Could be that bash is often outdated in mac? Will try it on a mac soon.

**Comment by lcook** [comment]
Please see #658, cheers.
