### ISSUE TITLE
Provide option to sort based on user created custom column

### ISSUE THREAD

**Issue by ChillarAnand** [sayanarijit/xplr#674]
Thanks for the great work on xplr.

I have created a custom called [line_count in xplr as described in this post](https://avilpage.com/2023/11/add-column-for-row-count-in-file-manager.html).

However, I couldn't find any option or a way to customize on how to sort based on this column.

It would be great if xplr could sort files based on user-created columns.

**Comment by sayanarijit** [comment]
Cool post. Unfortunately, sorting based on custom column isn't supported, and the implementation isn't trivial, so I guess it's out of scope for this project.

**Comment by sayanarijit** [comment]
As a side note, you might want to cache the function call result by file path and file modified time to make the rendering faster.

**Comment by ChillarAnand** [comment]
> As a side note, you might want to cache the function call result by file path and file modified time to make the rendering faster.

Will do that. Thanks for the tip.
