### ISSUE TITLE
Mapping function keys higher than F12 does not work

### ISSUE THREAD

**Issue by smackesey** [sayanarijit/xplr#681]
When I try to map F13 or higher, it shows up in the "Help" pane but pressing the key shows "key map not found".

**Comment by sayanarijit** [comment]
I didn’t think there would be function keys higher than f12. Should be an easy fix.

**Comment by sayanarijit** [comment]
If you have such keyboard, you can maybe try [updating input.rs](https://github.com/sayanarijit/xplr/blob/dev/src/input.rs) and let me know how it goes.

**Comment by sayanarijit** [comment]
Done in https://github.com/sayanarijit/xplr/releases/tag/v0.21.4
