### ISSUE TITLE
closing `xplr` with `q` or closing the terminal window closes any files opened in gui

### ISSUE THREAD

**Issue by Anomalocaridid** [sayanarijit/xplr#689]
When I open files with `gx`, the programs they are open in are closed when I either close `xplr`'s terminal window or close `xplr` with `q`, but not when I close it with `enter`.

I expected it to not close the programs regardless of how I close xplr.

- OS version: NixOS unstable
- `xplr` version: 0.21.3
- window manager: Hyprland, built from commit 880996b05339ba87066958a517885f1941185269
- terminal: wezterm 20230712-072601-f4abf8fd

**Comment by sayanarijit** [comment]
I couldn't reproduce in my NixOS with KDE (xorg). Maybe Hyperland issue?

**Comment by sayanarijit** [comment]
NixOS + KDE Wayland also works fine.

**Comment by Anomalocaridid** [comment]
After taking another look at it, I realized I should have mentioned how I was opening `xplr` because that appears to have an effect. Sorry about that.

I have a Hyprland keybind that opens it using the following command:
`wezterm start -- xplr`

It also appears to do the same thing if I have `wezterm` run it through a shell rather than directly:
`wezterm start -- fish -c 'xplr'`

`xplr` does, in fact, behave as expected if I manually run the command in a terminal shell instead.

It also works as expected if I modify the above command to use `-C` instead of `-c` so that `fish` loads my config before running `xplr`, but then that does not have the benefit of closing the terminal window when I am done with `xplr`.

**Comment by Anomalocaridid** [comment]
This appears to occurs with other terminal file managers as well. I think it might be caused by me shadowing `xdg-open` with a script running a different resource opener, `handlr`. Regardless, this does not appear to be an issue with `xplr`.
