### ISSUE TITLE
Installing in Termux

### ISSUE THREAD

**Issue by b9Joker108** [sayanarijit/xplr#699]
I noted that xplr has not been well-tested in Termux, but I tried to install it anyway, but no success:

’’’zsh
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/data/data/com.termux/files/usr/lib/rustlib/aarch64-linux-android/bin:/data/data/com.termux/files/home/.zi/polaris/sbin:/data/data/com.termux/files/home/.zi/polaris/bin:/data/data/com.termux/files/home/.local/bin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/texlive:/data/data/com.termux/files/home/install/bin" VSLANG="1033" "cc" "/data/data/com.termux/files/usr/tmp/rustcZLmwHU/symbols.o" "/data/data/com.termux/files/usr/tmp/cargo-installAz6mSa/release/deps/xplr-b7a301bd61899e8c.xplr.a4d550371f6c6aea-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/data/data/com.termux/files/usr/tmp/cargo-installAz6mSa/release/deps" "-L" "/data/data/com.termux/files/usr/tmp/cargo-installAz6mSa/release/build/mlua-sys-74884d2b8307d95a/out/luajit-build/lib" "-L" "/data/data/com.termux/files/usr/lib/rustlib/aarch64-linux-android/lib" "-Wl,-Bstatic" "/data/data/com.termux/files/usr/tmp/rustcZLmwHU/libmlua_sys-356dfd2f5e8104a9.rlib" "/data/data/com.termux/files/usr/lib/rustlib/aarch64-linux-android/lib/libcompiler_builtins-d269850cd60e0323.rlib" "-Wl,-Bdynamic" "-ldl" "-llog" "-lunwind" "-ldl" "-lm" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/data/data/com.termux/files/usr/lib/rustlib/aarch64-linux-android/lib" "-o" "/data/data/com.termux/files/usr/tmp/cargo-installAz6mSa/release/deps/xplr-b7a301bd61899e8c" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-all" "-nodefaultlibs"
  = note: ld.lld: error: undefined symbol: __clear_cache
          >>> referenced by lj_mcode.c
          >>>               lj_mcode.o:(lj_mcode_sync) in archive /data/data/com.termux/files/usr/tmp/rustcZLmwHU/libmlua_sys-356dfd2f5e8104a9.rlib
          cc: error: linker command failed with exit code 1 (use -v to see invocation)

error: could not compile `xplr` (bin "xplr") due to 1 previous error
error: failed to compile `xplr v0.21.5`, intermediate artifacts can be found at `/data/data/com.termux/files/usr/tmp/cargo-installAz6mSa`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
’’’

I don't use cargo much, so am not really aware of its ins and outs. I am disappointed that xplr didn't install.

**Comment by sayanarijit** [comment]
Thanks for reporting. Termux keeps breaking. Will remove the section.

**Comment by b9Joker108** [comment]
I am very disappointed. I just tried again, for the hell of it. Still no success.

**Comment by sayanarijit** [comment]
I have removed the termux section from the docs, since maintaining termux support is proving to be a burden. Termux enthusiasts overlapping xplr users are welcome to package xplr in the termux repo.
