### ISSUE TITLE
xplr crashes if terminal has <= 94 columns

### ISSUE THREAD

**Issue by abhinavnatarajan** [sayanarijit/xplr#718]
There is a particular folder on my computer, that if I open up in xplr, will cause a crash if the terminal window has 94 or fewer columns.
This does not happen when the number of columns is greater than or equal or 95.

I am running wezterm (20240203-110809-5046fc22). In both previews below, I try to open the folder named 'homological_algebra' using xplr.

https://github.com/sayanarijit/xplr/assets/25101966/76bb1f77-a40c-47b5-97c0-1bc255b3c115

https://github.com/sayanarijit/xplr/assets/25101966/3f23fb51-003e-4718-90aa-476c37c7f7a7

**Comment by sayanarijit** [comment]
Very interesting. Could be a ratatui issue. Not sure. Is there a file with a very long name?

**Comment by abhinavnatarajan** [comment]
Not really, all the file names are at most 30 characters. The issue is likely an [upstream bug](https://github.com/ratatui-org/ratatui/issues/1032) in `ratatui`, and the [fix](https://github.com/ratatui-org/ratatui/pull/1089) has not yet made its way to a release. I will try building with the latest nightly version of `ratatui` to check if the issue persists.

**Comment by abhinavnatarajan** [comment]
I can confirm that the issue is resolved when using the latest commit of `ratatui`, so perhaps this issue can be closed when they next release.

**Comment by sayanarijit** [comment]
Let’s keep it open till the next release, so that others can see this.

**Comment by abhinavnatarajan** [comment]
`ratatui v0.26.3` has been [released](https://github.com/ratatui-org/ratatui/releases/tag/v0.26.3) and contains the relevant fix.
