### ISSUE TITLE
How to start directly in search mode?

### ISSUE THREAD

**Issue by shellwhale** [sayanarijit/xplr#721]
I would like to start directly on search mode (without having to type `/`).

Is that possible ?
I tried with the following parameters :

```
xplr --on-load 'SearchFuzzy'
error: invalid type: unit variant, expected newtype variant
````

**Comment by sayanarijit** [comment]
You can enter `xplr --on-load 'SearchFuzzy: foo'` but you won't be in the search mode.
To enter search mode, run:
```
xplr --on-load 'SwitchModeBuiltin: search' 'BufferInput: foo' SearchFuzzyFromInput
```

**Comment by sayanarijit** [comment]
Actually, I missed the `ExplorePwd` message, which needs to be passed at the end in both cases.

**Comment by shellwhale** [comment]
Works great, thanks
