### ISSUE TITLE
Brew formula for osx/linux

### ISSUE THREAD

**Issue by rjcoelho** [sayanarijit/xplr#74]
To increase project usage

**Comment by sayanarijit** [comment]
Hey @alebcay is it possible please?

**Comment by rjcoelho** [comment]
This is a rust project, so take it from say https://github.com/sharkdp/fd

https://formulae.brew.sh/api/formula/fd.json

**Comment by sayanarijit** [comment]
@rjcoelho Sorry I'm not much familiar with packaging, but isn't https://formulae.brew.sh/api/formula/xplr.json what you are looking for?

**Comment by rjcoelho** [comment]
You are correct! I didn't saw it on the installation docs. Thanks
