### ISSUE TITLE
Ability to preserve filter and operate on filtered results

### ISSUE THREAD

**Issue by maximbaz** [sayanarijit/xplr#75]
This is a feature that I think was very cool in `nnn`: apply a filter first, and then work on a "scoped" results.

For example, suppose I enter ~/Downloads directory with a gazillion of files, and I want to regain some space by removing large video files. I would hit `/` and type `.mp4`, and at this point I only see video files. Now I would like to work on this filtered list, e.g. go through them with `j/k`, select some with `Space`, then delete the selection. If I leave the folder and come back, of course I should be able to see full folder again, filter should be forgotten.

Currently, after filtering with `.mp4` filter I can go up and down with arrow keys, not with `j/k`, but filter is still active, so I cannot really select files and delete them. And if I press Enter, then filter will be cancelled.

To be clear, I like the current Enter behavior, it jumps to the search result and I find that useful. But we could maybe have a different shortcut to exit filter mode, similar to Enter, but one that would preserve the filtered results.

What do you think?

**Comment by sayanarijit** [comment]
To be honest I thought that was a bug in nnn.
But I think it'll be good to have. Fyi you can currently do this by custom mapping.

**Comment by maximbaz** [comment]
That's true, I could define some of the most needed keys 🤔 `j/k` would not be possible, but other keys will. But if you think it will in in core, then I can wait for sure 🙂

**Comment by maximbaz** [comment]
Beautifully fixed with #76
