### ISSUE TITLE
Behavior of Backspace key

### ISSUE THREAD

**Issue by maximbaz** [sayanarijit/xplr#77]
Currently Backspace is not very intuitive:

1. You open search with `/` and start typing, you make a typo, press Backspace and uh-oh everything is gone
2. You open filter with `f` and start typing, make a typo, press Backspace, and not only all your filters are gone, but even default "hide hidden files" is gone too

What if we leave Backspace with "usual" behavior of removing one char to the left, and instead find a new binding for "clear everything"? Similar to "Ctrl+R" for reset, maybe "Ctrl+L" (like clear in terminal) or "Ctrl+U" (like in some shells, clear a line)?

**Comment by sayanarijit** [comment]
I also feel the same. But not sure if `xplr` should have readline like features in-built or this should be an extension/plugin.
Or I can only implement the most used features inbuilt.

**Comment by maximbaz** [comment]
Or https://crates.io/crates/rustyline/? 😜

**Comment by sayanarijit** [comment]
But it will require transition to another screen to read input.

**Comment by maximbaz** [comment]
Huh ok, I didn't realize this... In any case I feel like this behavior would confuse every user who will try to filter or search or sort, so maybe it does make sense to have at least basic support built-in, but at the same time try to be pragmatic and don't go completely overboard 🙂

**Comment by sayanarijit** [comment]
Hey @maximbaz, I ended up adding support for readline-like input buffer https://github.com/sayanarijit/xplr/pull/397.

This should remove a lot of boilerplate code for handling `ctrl-w`, `ctrl-u`, `backspace` etc. Please review if possible.
