### ISSUE TITLE
Format when disabling icons

### ISSUE THREAD

**Issue by maximbaz** [sayanarijit/xplr#78]
Tiny question, I would have sent a PR but got stuck a little, thought it will be faster to ask 🙂 

I want to try to completely disable icons (which is easy, I just set `icon: ""`), but then there is an extra space, like so: 
`[ filename]` 

To remove it, I could just join these two lines to be on a same line, and it helps:

https://github.com/sayanarijit/xplr/blob/f582f49ad8a7ee267014bb3aab02bbdfd5f3cedb/src/config.yml#L64-L65

But to make it better I thought we can improve this default value, to something like `{{{if icon-is-not-empty}}} {{{/if}}}` but I don't know how to do that 😄 

Curiously grepping for `isSymlink` (wanted to use as an example) finds nothing... feels like magic 😅

**Comment by sayanarijit** [comment]
You can set icon value to `" "`

**Comment by sayanarijit** [comment]
or maybe `{#ifEq meta.icon ""}`

**Comment by sayanarijit** [comment]
BTW the space is probably coming from the line gap

**Comment by maximbaz** [comment]
Thanks, I didn't know how to google this, I found that it is handlebars syntax 😄
