### ISSUE TITLE
Should selection be a set, to prevent duplicates?

### ISSUE THREAD

**Issue by maximbaz** [sayanarijit/xplr#81]
- Pressing `Ctrl+a` multiple times adds the same time multiple times
- After selecting a few files with space, and then selecting with `Ctrl+a` will also add duplicates

If we keep selection in a "set" structure, it should automatically take care of duplicates. Question is, is it a good idea, or will this break some scenarios?

**Comment by sayanarijit** [comment]
Yes. I was actually waiting for something to force me into using `IndexSet` external library.

**Comment by sayanarijit** [comment]
But then I included it, I forgot to port the selection to this.
