### ISSUE TITLE
xplr v0.5.5 complains about incompatible configuration version

### ISSUE THREAD

**Issue by alebcay** [sayanarijit/xplr#97]
After building `xplr` v0.5.5, running it results in the message:

```
error: incompatible configuration version in /Users/caleb/Library/Application Support/xplr/config.yml
                You config version is : v0.5.5
                Required version is   : v0.5.5
                Visit https://github.com/sayanarijit/xplr/wiki/Upgrade-Guide
```

I had no config file at that location (the entire `xplr` folder did not exist), so I tried downloading the default/example config from https://github.com/sayanarijit/xplr/blob/main/src/config.yml and placing it there. However, I still receive the same result when trying to run `xplr`.

**Comment by sayanarijit** [comment]
My bad. I'm never direct pushing again.

**Comment by alebcay** [comment]
No worries. Thanks for the quick follow-up!
